### ISSUE TITLE
Scaler Crashes almost immediately

### ISSUE THREAD

**Issue by cameronleger** [robbert-vdh/yabridge#10]
I _might_ be able to assist with getting the plugin if you cannot get a demo; I didn't know it was locked behind an account.

There's something interesting about Bitwig's scanning on this, because it can scan it without crashing, so it shows up, but it crashes whenever it's added. Whereas Carla and Renoise both crash while scanning it, so they're doing a step during the scan that Bitwig is not.

Carla Log: https://pastebin.com/rHk73UuW
Bitwig Log: https://pastebin.com/cXTW1fNj

One other weird thing that seems to be related to this: the unsecapp.exe process for the prefix will get 'locked' at 400% CPU usage; I guess that's four-cores maxed out?

**Comment by robbert-vdh** [comment]
Okay this is a bit of a dumb one. Scaler reported to have 64 audio inputs channels,  and the maximum number of audio channels I had set for the data serialization was 32. This was too low of a value anyway since there are plugins such as Kontakt that support up to 64 input and output channels. I've fixed this in the last commit. Let me know if there are still any issues with Scaler!

**Comment by cameronleger** [comment]
OK so now it opens and runs and doesn't crash on MIDI stuff! I've been waiting for a fix for that for a long time!

There is now one weird issue with the GUI. The same thing happens with Gatekeeper as another example, but it _doesn't_ happen with Cthulu.

The _first_ click on the GUI locks the mouse to that window. While the mouse has 100% movement outside of the window, no hover/click events are sent anywhere else _except_ to the VST's window. The whole screen area is then "relative" to the VST's window, such that top-left of the screen is really top-left of the VST's window. All of that hover/click works with the VST, just offset/relative to the screen not the window.

The only way I found to get out of that state is to change workspaces and then back. I had to do that with a hotkey since the mouse won't affect anything but the VST's window.

**Comment by robbert-vdh** [comment]
In what host does that happen? I can't replicate it in Bitwig Studio 3.1 and 3.2 beta 3/4. The one time I saw similar behavior while I was developing yabridge was in REAPER when the plugin window did not reparent correctly. I am using the GTK3 theming option of Wine Staging, not sure if that would make a difference.

**Comment by cameronleger** [comment]
Both Bitwig and Carla. That's a fair point on the setting; I always have that enabled since it seems to solve a few things. I just checked and it is set! However, both Gatekeeper and Scaler come from the same wineprefix, whereas Cthulu is in another... there's clearly something going on with that, instead of being specific to those plugins.

**Comment by cameronleger** [comment]
Both the "allow the window manager to ..." options :D all seems good to me now!

**Comment by robbert-vdh** [comment]
Ah great! Those are the defaults, which is probably why I couldn't place really place the behavior you were seeing! We're doing a bit of X11 trickery to get the editor windows to play nicely, so having those options disabled will definitely break the editor windows. There's actually a sort of proxy window large enough to span your entire monitor that the actual Windows VST plugin window is embedded into, and then we reparent that window to the Window the DAW gives us. If Wine wouldn't let us manage that proxy window then that would definitely the behavior you were seeing since it will then cover the entire screen.

**Comment by robbert-vdh** [comment]
I just released yabridge 1.1.0 which should fix the audio channel related issue. Feel free to create a new issue if there are any other issues with Scaler or similar plugins.
