### ISSUE TITLE
Explicitly mark dlls to be treated as plugins

### ISSUE THREAD

**Issue by iandwelker** [robbert-vdh/yabridge#105]
When I run `yabridgectl sync`, it outputs the expected message and says that it skipped ~200 non-plugin .dll files. However, many of these dlls actually are plugins, and I can't seem to find a way to force it to treat them as such. In cases such as this, it would be nice to bypass whatever methods yabridge normally uses to detect if a dll is a plugin, and attempt to handle it as a plugin anyways (and create a `.so`, all that, etc).

Is this feature already implemented in some way? And if not, would this be possible? 

(Thanks a ton for this program, by the way &mdash; audio production was the only thing keeping me from dumping windows, so I'm very glad that I can finally stop dualbooting :)

**Comment by robbert-vdh** [comment]
Those .dll files most definitely aren't VST2 plugins! Can you name an example of such a file? If you run `yabridgectl sync --verbose`, you'll get a list of skipped files near the end of the output. In my case for instance, I get a bunch of `.../iZotope7/iZSomethingSomething.dll` files. These libraries are loaded by the actual VST2 and VST3 plugins at runtime (which have more human readable with spaces and don't start with `iZ`). Yabridgectl checks the entry points defined by the .dll/.vst3 file (`VSTPluginMain`, `main_plugin` and `main` for VST2 plugins, and `GetPluginFactory` for VST3 plugins) to detect whether a library is a VST2 plugin, a VST3 plugin, or some other unrelated library. If yabridgectl won't detect that it's a plugin, then yabridge also won't be able to load it because it doesn't export any of the VST2 or VST3 entry point functions.

And great to hear that you're liking yabridge! :smile:

**Comment by iandwelker** [comment]
For example, about half of the plugins that come with FL Studio are processed as VSTs, and about half aren't. Sawer, Sakura, Morphine, Toxic Biohazard, and a few others are processed just fine (both the `plugin.dll` and `plugin_x64.dll` files), but many others, such as Harmor, Harmless, Sytrus, 3x Osc, aren't. They're explicitly listed as skipped files, both their `plugin.dll` and `plugin_x64.dll` files.

Is there some tool that I could use to analyze them to verify they actually have the entry points that you mentioned? Or would you like to take a look at them?

**Comment by robbert-vdh** [comment]
The plugins that come with FL Studio are not VST2 or VST3 plugins, but rather they are written using FL Studio's own plugin format. There were VST2 versions of most of those plugins available, but you need to buy them separately and Image-Line stopped supporting (and selling) them.

You can use `winedump -j export path/to/a/plugin.dll` to find out which entry points the plugin defines. VST2 plugins define either `VSTPluginMain`, `main_plugin`, or `main`, and VST3 plugins define `GetPluginFactory`.

**Comment by iandwelker** [comment]
Oh, I had no idea; I assumed that since some worked, all should, but I ran `winedump` on them and see that they definitely don't export those entry points. Thanks for letting me know about that.

Are there any plans to support FL Studio's format of plugins? I understand it may be a large undertaking, so I don't expect they'll be supported, but if it's easily doable, I would appreciate that feature.

**Comment by robbert-vdh** [comment]
That won't be possible, since they're written in a propietary undocumented format and there are no other hosts capable of loading those plugins. Just like the GIMP is not able to load Photoshop's tools.

**Comment by iandwelker** [comment]
Completely understandable. Thanks again for making this tool! I'll close the issue, since there's nothing more to be done.
