### ISSUE TITLE
MODO DRUM Performance Issues.

### ISSUE THREAD

**Issue by emmetoneillpdx** [robbert-vdh/yabridge#109]
Hi Robbert!

**Problem description**
I'm having a problem with performance while running [IK Multimedia's MODO DRUM](https://www.ikmultimedia.com/products/mododrum/) through Bitwig Studio 4 and yabridge 3.2.0. 

Basically I'm seeing frequent spikes in Bitwig's built-in DSP meter and hearing a bunch of xrun clicks/pops.

When I run the standalone version of MODO DRUM through wine (with the same buffer size and sample rate) it seems to have no problem with performance at all, so I'm guessing the issue is in the bridge instead of wine in general.

**What did you try?**
It could just be the placebo effect, but I tried using the `cache_time_info = true` setting that you added to address some performance issues with SWAM Cellos, and I feel like it may have _slightly_ improved the performance. 
Could be in my head though. ;)

**System information**
- Plugin: IK Multimedia MODO DRUM
- Plugin type: VST3
- Host: Bitwig Studio
- Operating system: Fedora 34
- Wine version: wine-6.5 (Staging)
- Audio: Pipewire (256 samples @ 48000 Hz)
- Installation method: symlinks/copies
- yabridge version: 3.2.0
- yabridgectl version: 3.2.0

**Debug log**
[I've attached my yabridge.log file.](https://github.com/robbert-vdh/yabridge/files/6565688/yabridge.log)

I've also captured a short video of the issue where you can see the spikes in Bitwig's DSP graph, let me know if that would help and I can try to share it.

Thanks a ton.
Emmet

**Comment by robbert-vdh** [comment]
Hi Emmet!

There are a few things you can try, in order of importance:

1. Try upgrading to the latest master branch version of yabridge. There have been a lot of [still unreleased changes](https://github.com/robbert-vdh/yabridge/blob/master/CHANGELOG.md) since yabridge 3.2.0. You can grab the lastest build from the [automated builds page](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) (you need to be logged in to GitHub to download). Just select the latest build there, download the yabridge and yabridgectl binaries at the bottom of the page, replace your existing files in `~/.local/share` (these are .tar.gz files inside of .zip files because GitHub is dumb), and finally rerun `~/.local/share/yabridge/yabridgectl sync`.
2. You don't seem to have realtime priviliges set up, and you may also not be using a kernel with the `PREEMPT` patch set enabled. This is very important here since the actual plugin lives in another process, so being able to quickly switch between Bitwig's audio engine process, Bitwig's plugin host process, and yabridge's plugin host process is crucial. You can find a checklist with this and a lot of other useful tweaks in [yabridge's readme](https://github.com/robbert-vdh/yabridge#performance-tuning).
3. On some systems Bitwig's sandboxing can also cause additional xruns. It doesn't happen here (on Manjaro), but there are [quite a few reports](https://www.kvraudio.com/forum/viewtopic.php?f=259&t=517899) about this. Try switching to the 'Within Bitwig' plug-in hosting mode if there are still issues and restart the audio engine. (this does mean that there's no crash protection for individual plugins anymore)

(oh and also, the `cache_time_info` option no longer exists in yabridge 3.2.0, so that's definitely placebo :grin:)

**Comment by emmetoneillpdx** [comment]
> Try upgrading to the latest master branch version of yabridge. There have been a lot of still unreleased changes since yabridge 3.2.0. You can grab the lastest build from the automated builds page (you need to be logged in to GitHub to download). Just select the latest build there, download the yabridge and yabridgectl binaries at the bottom of the page, replace your existing files in ~/.local/share (these are .tar.gz files inside of .zip files because GitHub is dumb), and finally rerun ~/.local/share/yabridge/yabridgectl sync.

Ok, tried it using the latest build. No noticeable difference, I think...

> You don't seem to have realtime priviliges set up, and you may also not be using a kernel with the PREEMPT patch set enabled. This is very important here since the actual plugin lives in another process, so being able to quickly switch between Bitwig's audio engine process, Bitwig's plugin host process, and yabridge's plugin host process is crucial. You can find a checklist with this and a lot of other useful tweaks in yabridge's readme.

Yeah, that makes sense!

I'm pretty new to Fedora and PipeWire so I had to ask about this today on the #pipewire IRC channel. The person who responded seemed to be suggesting that PipeWire has real-time privileges out of the box using something called rtkit (which I guess is a D-Bus service for granting real-time scheduling to processes), and that I probably don't need to do anything special like jack does. 

So, I'm not exactly sure what I need to do about realtime and whether I need a different kernel... 
Are you familiar with PipeWire at all?

> On some systems Bitwig's sandboxing can also cause additional xruns. It doesn't happen here (on Manjaro), but there are quite a few reports about this. Try switching to the 'Within Bitwig' plug-in hosting mode if there are still issues and restart the audio engine. (this does mean that there's no crash protection for individual plugins anymore)

I gave this a try too and couldn't notice any significant difference. 
(Beyond my tendency towards placebo, of course. :wink:)

**Comment by noisecode3** [comment]
try enable real-time thru PAM in /etc/security/limits.conf
I think that will give yabridge real-time privileges too
you're kernel will probably have this but its best to check you're kernel .config
Its only my input on the matter you should listen more to Robbert here

**Comment by robbert-vdh** [comment]
> I'm pretty new to Fedora and PipeWire so I had to ask about this today on the #pipewire IRC channel. The person who responded seemed to be suggesting that PipeWire has real-time privileges out of the box using something called rtkit (which I guess is a D-Bus service for granting real-time scheduling to processes), and that I probably don't need to do anything special like jack does.
>
> So, I'm not exactly sure what I need to do about realtime and whether I need a different kernel...
Are you familiar with PipeWire at all?

The person responding probably isn't familiar with pro audio. PipeWire (and for instance Firefox for that matter) use rtkit as a way to get a process to run under the `SCHED_FIFO` scheduling policy, but that does not mean that your user has realtime priviliges. Both Bitwig and yabridge will try to use this scheduler through `sched_setscheduler(0, SCHED_FIFO, ...);`, and that won't work unless your user is allowed to do that. Most distros will configure either the `audio` or the `realtime` group to have these priviliges through a config file in `/etc/security/limits.d` (after installing either the JACK package some dedicated package depending on the distro), but you'd have to look up how Fedora does this. After this has been set up, you should be able to run `chrt -f 60 whoami` and that should print your username. And you also need a kernel with the `PREEMPT` patch set as mentioned in that link I posted. You can verify that this is the case by running `uname -a`, which should include either `PREEMPT` or `PREEMPT RT`.

Rtkit can also cause yabridge to crash because it was never meant to be used in pro audio (hence why no DAWs use it). On some distros it's configured to set a low `RLIMIT_RTTIME` limit by default, meaning that a realtime process can run uninterrupted for only so long before the scheduler kills it. I think this is mainly an issue on Arch and Manjaro but it can happen on every distro. The latest master branch versions of yabridge will print a huge warning on startup (visible in `~/.BitwigStudio/log/engine.log`) when `RLIMIT_RTTIME`'s current limit is 30 seconds or less, so if yabridge starts crashing after these changes, then PipeWire is likely to blame here.

**Comment by emmetoneillpdx** [comment]
> PipeWire (and for instance Firefox for that matter) use rtkit as a way to get a process to run under the SCHED_FIFO scheduling policy, but that does not mean that your user has realtime priviliges. Both Bitwig and yabridge will try to use this scheduler through sched_setscheduler(0, SCHED_FIFO, ...);, and that won't work unless your user is allowed to do that. Most distros will configure either the audio or the realtime group to have these priviliges through a config file in /etc/security/limits.d (after installing either the JACK package some dedicated package depending on the distro), but you'd have to look up how Fedora does this. After this has been set up, you should be able to run chrt -f 60 whoami and that should print your username.

Ok, that makes perfect sense. 

I've gone ahead and set up and `audio` group with realtime privileges and `chrt -f 60 whoami` shows my username, so I have at least that much set up correctly now.

> And you also need a kernel with the PREEMPT patch set as mentioned in that link I posted. You can verify that this is the case by running uname -a, which should include either PREEMPT or PREEMPT RT.

This part is still a sticking point for me right now, since it seems that there isn't a quick and easy way of getting a preempt/rt-patched kernel in Fedora 34. [It seems that Stanford's CCRMA used to distribute one from their "Planet CCRMA" repository](http://ccrma.stanford.edu/planetccrma/software/installplanetthirty.html), but it's a little bit out of date and I can't quite get it working on Fedora 34. I'll keep looking into this when I have some time...

>Rtkit can also cause yabridge to crash because it was never meant to be used in pro audio (hence why no DAWs use it). On some distros it's configured to set a low RLIMIT_RTTIME limit by default, meaning that a realtime process can run uninterrupted for only so long before the scheduler kills it. I think this is mainly an issue on Arch and Manjaro but it can happen on every distro. The latest master branch versions of yabridge will print a huge warning on startup (visible in ~/.BitwigStudio/log/engine.log) when RLIMIT_RTTIME's current limit is 30 seconds or less, so if yabridge starts crashing after these changes, then PipeWire is likely to blame here.

And yeah, this seems to be a problem for me using PipeWire on Fedora with default settings. 

The default `rt.time` value that PipeWire uses is 200000us, which (as you described) is lower than yabridge needs it to be. This causes MODO DRUM and some other plugins that run through yabridge to crash due to timeout (I think) on loading.

The bigger problem is that I can't seem to change it no matter what I do! I've edited the "soft" and "hard" values in `pipewire.conf` and `jack.conf`, but yabridge continues to report that my RLIMIT_RTTIME is set to 200000us... I'll try to get in touch with some PipeWire people to see if I can resolve this somehow, since this seems to be a either a PW issue or another mistake in my configuration.

I appreciate all the help so far.

---

As an aside, I noticed that [MODO DRUM has a trial version available through the IK Multimedia launcher](https://www.ikmultimedia.com/demodownload/), if anyone else around here has the extra time, energy, or interest to see how it performs for them. (It's a nifty little physically modeled drum synthesizer, though the cymbals are sampled I think) :laughing:

**Comment by robbert-vdh** [comment]
> And yeah, this seems to be a problem for me using PipeWire on Fedora with default settings.
> 
> The default `rt.time` value that PipeWire uses is 200000us, which (as you described) is lower than yabridge needs it to be. This causes MODO DRUM and some other plugins that run through yabridge to crash due to timeout (I think) on loading.
> 
> The bigger problem is that I can't seem to change it no matter what I do! I've edited the "soft" and "hard" values in `pipewire.conf` and `jack.conf`, but yabridge continues to report that my RLIMIT_RTTIME is set to 200000us... I'll try to get in touch with some PipeWire people to see if I can resolve this somehow, since this seems to be a either a PW issue or another mistake in my configuration.

RIght now the easiest solution is to just not use PipeWire, and to just use JACK2 or raw ALSA. The very latest version of PipeWire gained a `module-rt` that you can use instead of `module-rtkit` (you'd need to modify all of the config files yourself). For rtkit you'd need to change the parameters passed to the rtkit service to increase or get rid of the `RTTIME` limit (-1 means infinite/unlimited).

**Comment by emmetoneillpdx** [comment]
Hey again, Robbert. I have good news (for me at least)! 

I've got **Pipewire 0.3.29 and Yabridge 3.3.0 working correctly together with real time privileges**, and the result is that MODO DRUM not only loads without crashing, but also performs significantly better, with minimal xruns at a very playable buffer size of 256@48000Hz. :grinning:

Here's what ultimately got me there:

0. Like you suggested, setup **realtime privileges** for my user in `/etc/security/limits.d/audio.conf` as described [here](https://jackaudio.org/faq/linux_rt_config.html).
1. Then I had to **copy a bunch of my PipeWire configuration files from `/usr/share/pipewire/` to `/etc/pipewire/`**, making sure to keep any intermediate directories if they existed. (I copied all of the .conf files that appeared after running `grep -r module-rtkit /usr/share/pipewire/`.)
2. Next, I **edited all of the configuration files that I just copied to `/etc/pipewire/`, replacing `libpipewire-module-rtkit` with `libpipewire-module-rt`** anywhere I could. I'm not sure if this step was strictly necessary, but I did it. (Pipewire 0.3.29 or newer)
3. Finally, I **set the `rt.time.soft` and `rt.time.hard` values in both `/etc/pipewire/pipewire.conf` as well as `/etc/pipewire/jack.conf` to 30000000** (30 seconds). Setting `pipewire.conf` alone did not work, and I haven't tried `jack.conf` on its own yet.
4. Of course, then restart the pipewire service or reboot for the changes to go into effect.

(I didn't manage to get a preempt/rt-patched kernel going, but so far it's working like a dream anyway.)

It would be nice if PipeWire was configured to play nice with Yabridge in real time out of the box, and maybe they can figure out a way to do that in the future, but for now I hope these instructions will be helpful to the next person who runs into this issue.

Thanks again for the help and the great tool for Linux musicians.

**Comment by diegombeltran** [comment]
Hi,

I tried this in Fedora 34. It definitely works better now, but I still get some xruns, crackling and popping sound sometimes, specially when other apps sound at the same time (I usually play the guitar on top of audios on Youtube). In my case the VST is STL Tonality. So, is this related to realtime kernel? Is there any other thing we could try to improve performance?

Thank you

**Comment by diegombeltran** [comment]
I'm sorry @robbert-vdh, should I open another ticket with my own data?

**Comment by robbert-vdh** [comment]
@diegombeltran That might be a good idea, just to save @emmetoneillpdx from some email spam. :sweat_smile:  You can also join us on the Discord, that might be easier.

Anyways, whatever you do, make sure you went through the things in the [performance tuning section](https://github.com/robbert-vdh/yabridge#performance-tuning) first, and if that didn't help could you then please show me yabridge's initializing output on your machine? No need to set `YABRIDGE_DEBUG_LEVEL` to anything, and you launch your DAW with `YABRIDGE_DEBUG_FILE` set to some path to have yabridge write its output there instead of to the terminal. It might also be a good idea to just double check this with a plugin that's known to work absolutely flawlessly under Wine, like ValhallaSupermassive!

**Comment by diegombeltran** [comment]
I will do in a couple of hours or so. Thank you for your support!
