### ISSUE TITLE
Bitwig 3.3 does not detect VST Plugins

### ISSUE THREAD

**Issue by aadilayub** [robbert-vdh/yabridge#111]
**Problem description**
Hi, so I was trying to get Spitfire Labs working in Bitwig with yabridge, but after installing the plugins and running `yabridge sync` etc, I get the following error when Bitwig scans the plugins directory:

![image](https://user-images.githubusercontent.com/31581044/120593045-52305f00-c458-11eb-974a-54512d50f9d3.png)

```
/home/aadil/.wine/drive_c/Program Files (x86)/VstPlugins/LABS (32 Bit).so

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load VST 2 plug-in /home/aadil/.wine/drive_c/Program Files (x86)/VstPlugins/LABS (32 Bit).so: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory
-------------------------------------------------------------------

/home/aadil/.wine/drive_c/Program Files/VstPlugins/LABS (64 Bit).so

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load VST 2 plug-in /home/aadil/.wine/drive_c/Program Files/VstPlugins/LABS (64 Bit).so: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory
-------------------------------------------------------------------


```

**System information**
- Plugin: Spitfire Audio
- Plugin type: VST2
- Host: Bitwig Studio 3.3
- Operating system: Fedora 34
- Wine version: Wine 6.9
- Audio: PulseAudio
- Installation method: [copr package](https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/builds/)/yabridgectl
- yabridge version: 3.2.1
- yabridgectl version: 3.2.0

**Comment by robbert-vdh** [comment]
> libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory

The version of yabridge you're using is built against Boost 1.75, so you need to have that version installed for it to work. If Fedora updated their Boost recently and you have a newer version installed, then you might want to install the `3.2.1-0.9.20210601.git712ef41.fc34 ` build from that repo (which is what will be yabridge 3.3.0 any day now, check out the changelog [here](https://github.com/robbert-vdh/yabridge/blob/master/CHANGELOG.md)).

**Comment by aadilayub** [comment]
Thanks for the response!

I checked and the version of boost I installed appears to be 1.75.0:

```
❯ sudo dnf install boost
[sudo] password for aadil: 
Last metadata expiration check: 0:10:26 ago on Fri 04 Jun 2021 05:09:25 AM PKT.
Package boost-1.75.0-4.fc34.x86_64 is already installed.
Package boost-1.75.0-4.fc34.i686 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by robbert-vdh** [comment]
I wouldn't be surprised if Fedora splits up the boost package, so you'd need to install `boost-filesystem` or something like that. You'll probably need to ask @plaimbock for help as he maintains that repo. He's also on the Discord. Oh and you'll likely also want to at least make sure to install the most recent package in that repo, since yabridge 3.3.0 got released yesterday.

**Comment by plaimbock** [comment]
Correct, boost is split up in several packages:
[patrick@x1-wifi ~]$ rpm -qf /usr/lib64/libboost_filesystem.so.1.75.0
boost-filesystem-(none):1.75.0-4.fc34.x86_64

My yabridge RPM has a 'Requires: boost-filesystem' so that package should be installed automatically when installing yabridge frmo my copr. Nevertheless make sure it is installed with:
$ sudo dnf install boost-filesystem

The yabridge 3.3.0 version is now available in my copr repo so please update and after that make sure to run:
$ yabridgectl sync

Do you use Wine 6.9 from the Fedora repo or from my copr repo? If you use Wine 6.9 from the Fedora repo than Spitfire plugins may not work due to this bug:
https://bugs.winehq.org/show_bug.cgi?id=51063

The Wine 6.9 in my copr repo has a revert which is a possible fix but I have not tested it yet and would not recommend using my Wine 6.9 copr. Wait for Wine 6.10 which should be out any day now and when Wine 6.10 shows up in my copr then try that one. See:
https://copr.fedorainfracloud.org/coprs/patrickl/

**Comment by plaimbock** [comment]
I updated all my coprs and installed them. Then installed LABS (installer version 3.2.20 in a clean wine prefix) and finally installed Mandolin and it worked fine in Bitwig 3.3.10.

List of coprs:
https://copr.fedorainfracloud.org/coprs/patrickl/fedora-wine-tkg-esync-fsync/
https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/
https://copr.fedorainfracloud.org/coprs/patrickl/wine-dxvk/
https://copr.fedorainfracloud.org/coprs/patrickl/fedora-kernel-preempt-fsync/

**Comment by robbert-vdh** [comment]
Closing this, since it's a Flatpak issue and not a yabridge issue per se.

**Comment by aadilayub** [comment]
@robbert-vdh how so? none of the people who commented here installed it as flatpak...

**Comment by plaimbock** [comment]
> @robbert-vdh how so? none of the people who commented here installed it as flatpak... I don't even think there is a flatpak package available for yabridge

AFAIK there is no yabridge flatpak. Possibly he meant the Bitiwg flatpak. I installed the Bitwig 4.0 Flatpak and only my vst3 plugins showed up. When I installed the Bitwig deb then vst3 and vst worked fine. So plugins not properly detected seems to be a Bitwig Flatpak issue and not a yabridge issue.

**Comment by robbert-vdh** [comment]
> @robbert-vdh how so? none of the people who commented here installed it as flatpak... I don't even think there is a flatpak package available for yabridge

Oops, I closed the wrong issue I guess, sorry! Were you still having issues?
