### ISSUE TITLE
Set custom Wine path

### ISSUE THREAD

**Issue by intrlocutr** [robbert-vdh/yabridge#115]
Hi,
First I would like to mention, I have been using this software for about a month and it is the best Windows VST experience I've ever had on Linux, and has inspired me to move my workflow away from Windows and Mac. Your work is much appreciated! For users like me who have multiple versions of Wine installed for other software, it would be even more awesome to have the ability to set a custom Wine path for yabridge e.g. in the `yabridge.toml` file--I personally prefer to use a more stable version of Wine as the system default. (I tried looking around in the code to see if I could potentially hard-code in my Wine path but I'm not sure where it would go.)

**edit**: by "Wine path" I'm referring to both the wine binary and the `WINEPREFIX`

Is this something that could be possible? Thanks again for your hard work on the project.

**Comment by robbert-vdh** [comment]
Hi!

This question has been asked on the Discord a few dozen times already, so I'll try to keep it short. Overriding the Wine version would need to be done per prefix, since it's not possible for two different wineservers from different Wine versions to be running at the same time in the same prefix. So implementing this within yabridge would mean adding Yet Another configuration file to the root of the Wine prefix for configuring this. In 99.9% of the use cases you would not need to mix Wine versions; simply installing the latest Wine version that's compatible with all of the plugins you want to use should be sufficient.

That's why I recommend keeping it simple and just installing the Wine version you're going to use system wide. If you _really_ need per-prefix Wine versions, then you can always use Wine's `WINELOADER` mechanism to use a script that selects a Wine binary based on `WINEPREFIX` (which will be set by yabridge if it wasn't already set).
