### ISSUE TITLE
Guis of Pulsar 1178 and PA AB Metric and Black box design and IK TR5 sunset reverb are unresponsive

### ISSUE THREAD

**Issue by durutti** [robbert-vdh/yabridge#118]
Hi Robbert,
I downloaded the latest version of yabridge, synched my plugins and on my test session
the guis of the above plugins are unresposnive which makes them unsable

I thought it was wine-6-12 staging so I downgraded again to 6.4 but the same issues occur

On the other hand drag n drop works on addictive drums2 so a huge thank you for that!

I am on the latest mixbus7 on ubuntu 20.04

yabridge version: 3.4.0
yabridgectl version: 3.4.0

**Comment by robbert-vdh** [comment]
Both the VST2 and VST3 versions of Pulsar 1178 work absolutely fine for me in Mixbus 7.0.140 with Wine Staging 6.12 and the latest master branch version of yabridge. Can you show a debug log from when this happens (in a session with only a single instance of the plugin loaded)? See the issue template for instructions on how to do this: https://github.com/robbert-vdh/yabridge/issues/new?assignees=&labels=&template=bug_report.md

**Comment by durutti** [comment]
What happened I was about ready to upload the logs

**Comment by robbert-vdh** [comment]
(great, GitHub even automatically closes issues if you mention the word 'fix' in the middle of a sentence)

Could you try again with the latest master branch version: https://github.com/robbert-vdh/yabridge/actions?query=branch%3Amaster

The workaround for JUCE bug causing plugin to freeze during resizing kind of broke the fix for that same JUCE bug causing Ardour/Mixbus to freeze because of a bug in Ardour. It's bugs all the way down!

**Comment by durutti** [comment]
A l
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6825776/yabridge.log)
ittle better but still laggy and not that much usable
Here is Pulsars log

**Comment by robbert-vdh** [comment]
I guess it's a different issue, since the thing I fixed isn't even mentioned in this log. There's nothing in there that would indicate any kind of issue on yabridge's side. You're talking about 'unresponsive', can you tell me what you mean by that? I assumed you meant that the plugin's GUI would just freeze at which point you'd need to forcefully kill Mixbus, but that doesn't appear to be the case here. Are you 100% sure this doesn't happen when you reinstall yabridge 3.3.1 and rerun `yabridgectl sync`?

**Comment by durutti** [comment]
You are right something is wrong with my nvidia-driver. It doesn't load correctly

**Comment by durutti** [comment]
Robbert, do you have any suggestion on how to make nvidia work. I have unistalled and re-installed the nvidia-drivers. nvidia-smi indicates that the driver is working, but ubuntu refuses to use it. In addition nvidia-settings doesnt dipslay all the informtaion as it used to. It is still working with renoir gpu
laptop hp omen with amd cpu (4800h), kernel xanmod 5.12.17, ubuntu 20.04

**Comment by robbert-vdh** [comment]
You'll need an NVIDIA driver linked against your kernel. If Xanmod doesn't provide that for you, then your only safe option is to use a DKMS module. Xanmod probably has a guide on how to do that (on Arch/Manjaro you'd use the `nvidia-all` PKGBUILD).

**Comment by durutti** [comment]
the issue I am facing is that the driver has the same behavior in both xanmod and the generic kernel
thank you

**Comment by robbert-vdh** [comment]
The driver is not being loaded. For the generic kernel installing the driver through Ubuntu's driver installer GUI should be sufficient. I don't use Ubuntu myself, so you'll probably need to ask for help on the Ubuntu forums/IRC.

**Comment by durutti** [comment]
I feel stupid, I was logging in wayland...
Everything works fine now
thank you
