### ISSUE TITLE
BBC Symphony Orchestra (Spitfire Audio) crashes after last update 3.4.0

### ISSUE THREAD

**Issue by sette15** [robbert-vdh/yabridge#119]
**Problem description**
BBC Symphony Orchestra crashes Reaper and MusE (the 2 DAW I tested) when added on a track. Both VST2 and VST3.
It worked without issues before the last update.

**System information**
- Plugin: BBC Symphony Orchestra (Spitfire Audio)
- Plugin type: VST2 and VST3
- Host: REAPER and MusE
- Operating system: openSUSE TW
- Wine version: Wine Staging 6.4
- Audio: JACK2
- yabridge version: yabridge 3.4.0
- yabridgectl version: yabridgectl 3.4.0

EDIT:
Please see attached log file.

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6835134/yabridge.log)

**Comment by robbert-vdh** [comment]
So, connecting to the shared memory audio buffers on the plugin side doesn't work for you. Can't think of a reason why that could be from the top of my head. Do you get some sort of `boost::system_error` exception printed to your terminal when launching REAPER from a terminal and loading the plugin? (without any `YABRIDGE_*` environment variables set)

**Comment by sette15** [comment]
Hi Robbert,
Thanks for your message.
I do have "terminate called after throwing an instance of '**boost::interprocess::interprocess_exception**', however anything mentioning "system_error".
Please see link below with the full output:
https://pastebin.com/WtBFLpVs

Thanks.

**Comment by robbert-vdh** [comment]
Does this only happen with BBSOD? (it should be the same for every plugin)

I've only seen that error just once, when a plugin didn't have any audio channels. It would seem odd to me that BBCSOD wouldn't have any audio channels, but you can at least give that a try by downloading the latest build from [this page](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) (select a commit with a green checkmark next to it and scroll down the build page), overwriting the existing files in `~/.local/share/yabridge` with the ones from the archive, and rerunning `yabridgectl sync`.

**Comment by sette15** [comment]
Hi Robbert,

yes it does happen with BBSOD only, as far as I tested. 
I've installed the "LABS Piano Soft" plugin from the same Spitfire Audio installer and it works without issues.

I tried to overwrite with a most recent yabridge and yabridgectl you suggested, but still no luck :(

**Comment by robbert-vdh** [comment]
Can you show me what the log looks like now? Run this in a terminal:

```bash
env YABRIDGE_DEBUG_LEVEL=2 carla-single vst3 "$HOME/.vst3/yabridge/BBC Symphony Orchestra (64 Bit).vst3" 2>&1 | tee /tmp/yabridge.log
```

And then after the plugin crashes, upload `/tmp/yabridge.log` to a pastebin (or you can drag-and-drop the file directly on the text field here on GitHub).

**Comment by sette15** [comment]
Absolutely.
Yes it does happen with both VST2 and VST3.
Please see attached the error message from Carla and the log file you asked for.
Thanks.
![Screenshot_20210718_165533](https://user-images.githubusercontent.com/87567555/126073963-8d2ad0fc-8dc0-4469-8526-9d0adc6f79bb.png)
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6836551/yabridge.log)

**Comment by robbert-vdh** [comment]
No, please run the command I posted above and upload the log file. I can't do much with just a screenshot of Carla. :sweat_smile:

**Comment by sette15** [comment]
I did attach the log already :) it's just below the screenshot

**Comment by robbert-vdh** [comment]
No, you attached the output of running `carla`, which doesn't contain any information. You need to run the `carla-single` command I posted in [this comment](https://github.com/robbert-vdh/yabridge/issues/119#issuecomment-882057762).

**Comment by sette15** [comment]
sorry, I forgot to mention that it doesn't give me any output.

andrea@localhost:~> env YABRIDGE_DEBUG_LEVEL=2 carla-single vst3 "$HOME/.vst3/yabridge/BBC Symphony Orchestra (64 Bit).vst3" 2>&1 | tee /tmp/yabridge.log
Carla library folder does not exist, is Carla installed?
andrea@localhost:~>

**Comment by robbert-vdh** [comment]
How did you install Carla? Something went wrong there. Alternatively you can also open the regular version of carla and drag-and-drop the .so file onto Carla, but the issue with that is that the output will be in the Log tab, and when Carla freezes you cannot go to that tab, so you should really try to fix your Carla installation first.

**Comment by robbert-vdh** [comment]
If you installed Carla from a package, then that package is broken. You can probably figure something out by running:

```bash
grep INSTALL_PREFIX "$(which carla-single)"
```

And checking whether that `INSTALL_PREFIX` directory contains a directory called `lib`, which should in turn contain a directory called `carla`, which finally contains a file called `carla-bridge-native`.

**Comment by sette15** [comment]
I did install Carla by GeekosDAW repo. I did try to open the regular carla version and drag-and-drop the .so and the screenshot I attached previously is the only output I can get. :(

that's my output for the command you gave me:

INSTALL_PREFIX = "/usr"
CARLA_LIBDIR = os.path.join(INSTALL_PREFIX, "lib", "carla")
CARLA_RESDIR = os.path.join(INSTALL_PREFIX, "share", "carla", "resources")

**Comment by robbert-vdh** [comment]
Falktx suggested that you may have installed a backend-only version of Carla (I didn't know that that was a thing), which means that it can't load any plugins out of the box. There's likely some other package you need to install before Carla is able to load plugins. The package is likely called something like `carla-bridge-native` or `carla-bridges` or something like that.

**Comment by sette15** [comment]
I do have `carla-bridges` and `carla-bridges-32bit` already installed.
what would you suggest to do?

**Comment by robbert-vdh** [comment]
I'm not very familiar with zypper, but I think `zypper se --provides /usr/lib/carla/carla-bridge-native` should tell you which package you need to install.

**Comment by sette15** [comment]
it's correct, but it doesn't give me any output.
andrea@localhost:~> sudo zypper se --provides /usr/lib/carla/carla-bridge-native
Loading repository data...
Reading installed packages...
No matching items found.
andrea@localhost:~>

**Comment by robbert-vdh** [comment]
Then I guess whoever is maintaining GeekosDaw's Carla package should add the missing file to the package, because without it you cannot use most of Carla. 

But I forgot that the plugin actually scans just fine in REAPER (I got two issues mixed up, sorry!). That makes things much easier. I've created a yabridge build that should be able to tell us exactly what went wrong here. To try this, you need to do the following:

1. Temporarily uninstall the yabridge package with zypper. You can reinstall it later, but we need to make sure that you're using the correct version of yabridge.
2. Go to [this page](https://github.com/robbert-vdh/yabridge/actions?query=branch%3Aremoveme%2Fshm-tracing-redux), click on the topmost build, scroll down the page, and download the ` yabridge-3.4.0-*.tar.gz` and `yabridgectl-3.4.0-*.tar.gz` file.
3. Extract both files (twice, it's a tarball inside of a zip file because GitHub is dumb).
4. In the directory where you've extracted both files, run:
   ```bash
   mkdir -p ~/.local/share/yabridge
   mv yabridge/* yabridgectl/yabridgectl ~/.local/share/yabridge
   ```
5. Run `~/.local/share/yabridge/yabridgectl sync`
6. Open REAPER with `env YABRIDGE_DEBUG_LEVEL=2 reaper 2>&1 | tee /tmp/yabridge.log`
7. Insert BBCSOD on a track, and after the plugin crashes, upload `/tmp/yabridge.log` somewhere (you can drag-and-drop the file onto the reply field here).

You can reinstall the yabridge package when you're done and rerun `yabridgectl sync` to revert back to 3.4.0 if you want to.

**Comment by sette15** [comment]
Hi Rob, thank you so much.
Yes, it does scan just fine inside REAPER. It crashes only once I try to insert it in a track.
Please see attach the new log file.
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6836878/yabridge.log)

**Comment by robbert-vdh** [comment]
Okay, we finally got there. The shared memory gets set up correctly on the Wine side, but you're getting a `Resource temporarily unavailable` (`EAGAIN`) error on the plugin side (I forgot to rethrow the exception, which is why the plugin actually did more things but crashed after the audio processing). An `EAGAIN` error on `mmap()` means that the locked memory limit has been reached, which means that yabridge wouldn't be able to access the same memory on the plugin side as it did on the Wine side. To fix this, you need to set up realtime scheduling priviliges and memory locking for your user. REAPER also prints errors about these two things at the start of the log. I don't use OpenSUSE so I don't know how it's usually set up there, but GeekosDaw probably has a guide for you on how to set up your system for pro audio.

I'll add a large visible error for this situation to yabridge so it's easily spotted if it happens again for someone.

**Comment by OctarineSourcerer** [comment]
Just wanted to say that the super useful error message helped me easily know what was going on. If anyone else uses Arch and wants to handle this error without diving into config files, an easy way of doing it is installing the `realtime-privileges` package, and adding their user to the `realtime` group with `usermod -aG realtime <username>`. Log out and back in again, and you should be able to launch the plugin without crashing.

**Comment by robbert-vdh** [comment]
Awesome! Yeah I've also seen this pop up on the Renoise forum, goes to show that these error messages and warning are actually useful. :grin: 

I'll close this issue now that these warnings and errors are in the master branch.
