### ISSUE TITLE
Fonts don't show in Bitsonic Keyzone Classic

### ISSUE THREAD

**Issue by jameh** [robbert-vdh/yabridge#13]
I'm hoping you can help me debug this. I've tried using `winetricks corefonts`, and symlinking my system fonts like so (suggested on [Arch wiki](https://wiki.archlinux.org/index.php/Wine#Fonts)):

```
$ cd ${WINEPREFIX:-~/.wine}/drive_c/windows/Fonts && for i in /usr/share/fonts/**/*.{ttf,otf}; do ln -s "$i" ; done
```

but no fonts show in the GUI

here's the log: [yabridge.log](https://github.com/robbert-vdh/yabridge/files/4606935/yabridge.log)

**System information**
- Operating system: Arch Linux
- Wine version: Wine Staging 5.8
- Installation method: symlinks
- DAW: Bitwig Studio 3.1.3
- yabridge version: 1.1.2 (installed from AUR)

![1589156446](https://user-images.githubusercontent.com/1538657/81514224-ad8a2f00-92e2-11ea-9439-d36af890272f.png)

[VST download link](http://www.vst4free.com/free_vst.php?id=2848)

**Comment by robbert-vdh** [comment]
At some point I took the Hail Mary approach and installed the `ttf-ms-win10` package from the AUR. The good news is that the font is definitely somewhere in there:

![afbeelding](https://user-images.githubusercontent.com/748520/81550665-dfea6980-9380-11ea-9ed7-c64acc9fe5ba.png)

This was with a clean WIne prefix with only the Keyzone Classic synth installed. Luckily this also makes it a lot easier to track down which fonts it's using. Otherwise you'd have to use either `strace` or `WINEDEBUG=+relay` and that can be a hassle and a half haha. I don't know exactly which font it is using, but these are the font files currently loaded by either yabridge or wineserver:

```shell
❯ lsof -c wine -c yabridge | rg ttf
yabridge- 21161 robbert  mem       REG               8,18    147764 10490737 /usr/share/fonts/TTF/AkaashNormal.ttf
yabridge- 21161 robbert  mem       REG               8,18     65932 10490801 /usr/share/fonts/TTF/Vera.ttf
yabridge- 21161 robbert  mem       REG               8,18    137272 13521250 /usr/share/wine/fonts/tahomabd.ttf
yabridge- 21161 robbert  mem       REG               8,18    143884 13521249 /usr/share/wine/fonts/tahoma.ttf
wineserve 21166 robbert  144r      REG               8,18    147764 10490737 /usr/share/fonts/TTF/AkaashNormal.ttf
wineserve 21166 robbert  145r      REG               8,18     65932 10490801 /usr/share/fonts/TTF/Vera.ttf
```

You probably have to track down Vera.ttf. I've had other applications (iZotope's Neutron) outright refuse to work in the past when that font was absent. Let me know if you need more assistance!

By the way in the log file you're still using yabridge 1.1.0 rather than 1.1.2, not that that matters for these font issues.

**Comment by jameh** [comment]
Thank you! It seems to be `AkaashNormal.ttf`, which I found in [`ttf-indic-otf`](https://www.archlinux.org/packages/community/any/ttf-indic-otf/)

Yes oops, I checked yabridge version in the wrong way!

Maybe I'll get around to installing the win10 fonts at some point (:
