### ISSUE TITLE
Yabridge with self-contained and portable Wine versions

### ISSUE THREAD

**Issue by oldcastlehq** [robbert-vdh/yabridge#132]
Hi,

Installing Wine via Linux distro will get files all over your file system, and when you uninstall Wine, there are always quite a bit of left over. So, I found these two projects from the same guy https://github.com/Kron4ek/Wine-Builds  and https://github.com/Kron4ek/Conty. Both of them provide a "portable" Wine version. I wonder if yabridge could work with a portable Wine? That would help to keep things tidy and even make it easier to try Wine new versions. 

Cheers

**Comment by robbert-vdh** [comment]
Yabridge doesn't care where your Wine comes from, but doing that won't solve the "when you uninstall Wine, there are always quite a bit of left over" thing you are talking about. Uninstall Wine using your package manager will completely remove all of Wine's files that were installed through the package. But uninstalling a package will never remove user any data from your home directory since that would break systems left and right, so your `~/.wine` prefix will obviously remain in tact since that's not part of Wine.

**Comment by oldcastlehq** [comment]
Ok. Thanks!
