### ISSUE TITLE
AAS Chromaphone crashes when removing Objeq Delay from same track

### ISSUE THREAD

**Issue by fooltopia** [robbert-vdh/yabridge#137]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections my issue wasn't listed there

### Problem description

When I put AAS Chromaphone (Demo) and Objeq Delay (Full version) on the same track, and then remove Objeq Delay, Chromaphone crashes. This only seems to happen when I change the preset in Objeq Delay at least once. 

(hide_daw is set to true for both)

### What did you expect to happen?

Chromaphone should not crash

### What actually happened?

Chromaphone Crashes

### Operating system

Arch

### How did you install yabridge?

AUR

### yabridge version

3.5.2

### yabridgectl version

3.5.2

### Wine version

wine-6.14 (Staging)

### Plugin installation method

copies

### Plugin

AAS Chromaphone and Objeq Delay

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.0.1

### Desktop environment or WM

KDE Plasma 5.22 on Xorg

### GPU model

Geforce GTX 1050 TI

### GPU drivers and kernel

470.63.01 on 5.14.5-arch1-1

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/7188521/yabridge.log)

### Anything else?

Thanks for your great work!

**Comment by robbert-vdh** [comment]
This doesn't have anything to do with Chromaphone, but rather it's just Objeq Delay throwing an error on shutdown. Since the call to `IPluginBase::terminate()` for Objeq Delay never returns, Bitwig will be stuck waiting on that. The actual issue would boil down to that `00f4:err:sync:RtlLeaveCriticalSection section 00000000048700F0 is not acquired`. So you either ran into a Wine bug, or Objeq Delay is actually trying to release a mutex that it has not yet acquired. If it's a Wine bug, then you may need to report it if it hasn't been reported already on Wine's bug tracker, and I guess you could check if it also happens with either Wine Staging 6.4 or wine-tkg.

**Comment by fooltopia** [comment]
Thanks for looking into it. This didn't seem to happen when I was using it a while back, so maybe something in wine changed. I'm going to check wine staging 6.4.
