### ISSUE TITLE
"Bitwig Studio" is not responding

### ISSUE THREAD

**Issue by anoadragon453** [robbert-vdh/yabridge#14]
**Problem description**

![image](https://user-images.githubusercontent.com/1342360/81693625-17781500-9458-11ea-879e-37c37999603f.png)

![image](https://user-images.githubusercontent.com/1342360/81694370-27dcbf80-9459-11ea-9736-a1abfd76aad7.png)

I seem to keep getting reports from my DE/WM (GNOME3) that VST plugin windows are not responding. Strangely the notice disappears after about 5s, meaning that intermittent responses are being generated, just not quickly enough such that the DE's timeout gets reached. (This is all speculation from a programmer, I don't actually know how a window not responding is calculated).

Does yabridge already purposely report feedback to the host in some fashion, and could this not be happening quick enough for some reason?

Interestingly, I find that if I just open the VST plugin and leave it there, this problem does not occur. It's just as I start to use the VST interfact (clicking on menus, knobs, etc) does this happen. Which would be the opposite of what you'd probably expect.

**What did you expect to happen?**

A message not to pop up.

**What actually happened?**

The message pops up. It can be quite annoying as you're tweaking things as it blocks your input.

To be clear, the VST window isn't frozen at all, everything still responds fine. My DE just seems to think it's frozen.

**System information**
- Operating system: Manjaro
- Wine version: Wine Staging 5.6
- Installation method: copies
- yabridge version: 1.1.3

**Debug log**: https://gist.githubusercontent.com/anoadragon453/03d5292208d73005e7932e3ced37c6fd/raw/8228fc995d9dbea5f2e3cfca7ace0b98754cbd63/yabridge-full

The log is quite noisy. Issue occurred 1-3s before the log file ends.

**Comment by robbert-vdh** [comment]
I wonder what GNOME uses to detect that something is not responding. If it sometimes happens during GUI interaction, then I presume that it will also happen if you leave open the wavetable selection dropdown in Serum or when you drag a knob and keep holding the mouse button for 5 seconds, right? Since the message says 'Bitwig Studio' and not 'BitwigPluginHost' or something I assume that the plugin hosting mode in Bitwig is set to 'Within Bitwig'. If you set this to 'Individually' then this message will may disappear since it looks like the issue is that GNOME thinks Bitwig is freezing while it is waiting for the call to the Wine process to return (since all GUI interaction in the Win32 API is blocking).

**Comment by anoadragon453** [comment]
It's unfortunately a little tricky to reproduce. I tried switching back and forth between the plugin location options, but I'm not entirely sure what needs to be done to apply the option. But yes, I was set to Within Bitwig.

Presumably if I do 'Together' it would still work as it's separate from Bitwig at that point as well? I still received the message with Together... but again I'm not sure if this only applies when plugins are loaded, when Bitwig is restarted... if I need to clear the plugin cache etc.

But the theory sounds plausible.

**Comment by anoadragon453** [comment]
As an example, changing it to "Individually" and then restarting Bitwig Studio still causes the error, still stating that "Bitwig Studio" is not responding. :thinking:

**Comment by robbert-vdh** [comment]
You have to restart the audio engine in order to use the new setting (I think it used to do it for you, but that was probably causing issues), but it sounds like you've already figured it out! I think GNOME just think the application is not responding because it's waiting for the Wine process that's handling the GUI to reply. Most other VST bridges will have do some kind of busy wait/spinlock, but yabridge uses UNIX sockets and events to avoid wasting resources and to reduce latency. Apparently that '_X_ is not responding' thing GNOME is doing is just a bit overzealous. For instance it will also do this when you're debugging an application with GDB. I just quickly checked how GNOME detects when an application is not responding ([here](https://github.com/GNOME/mutter/blob/mainline/src/core/display.c) in the source of mutter under pings), and it just doesn't look compatible with the way Win32 GUI handling works. It will mark the parent window the plugin's editor's embedded into as non responsive even when the editor is actively processing events. I'm not sure if there's a way to disable this behavior in GNOME for specific windows without having to disable it altogether.

**Comment by anoadragon453** [comment]
Seems like there are some promising solutions mentioned here! https://askubuntu.com/a/1215995

I'll try them tomorrow, late here :)

**Comment by anoadragon453** [comment]
Well, raising the timeout to 60s seemed to work perfectly for me, no more notifications!

```
gsettings set org.gnome.mutter check-alive-timeout 60000
```

I'm tempted to close this issue as there is a workaround and it doesn't seem like something that yabridge can solve on it's own?

**Comment by robbert-vdh** [comment]
Yeah I don't think this is solvable on our side unless mutter has some sort of ping whitelist attribute we can set on the parent window so it doesn't mark the process owning it as non responsive. KDE Plasma has a similar mechanism for detecting frozen applications, but as far as I'm aware that will only start checking whether a window is still responsive when you actually try to interact with it (and in this case clicking on the parent window would cancel any Wine GUI interaction that was blocking Bitwig's own plugin window handling)

**Comment by anoadragon453** [comment]
Cool, will close then. Thanks for helping me debug it!
