### ISSUE TITLE
More solid wine UI 

### ISSUE THREAD

**Issue by guglielmofratticioli** [robbert-vdh/yabridge#152]
### Feature description

i have noticed that wine native apps have a less glitchy ui if I have the options “ allow window manager to control windows “ disabled , well I guess wine manages its windows better than Xfce or similar … I wonder if yabridge could make plugins floating windows to be controlled by wine :/

**Comment by robbert-vdh** [comment]
I'm not going to offer standalone windows as a feature because it's not a good user experience. There should not be any glitchiness when using the 'allow window manager to control windows' option though, if there are issues then that's probably caused by your window manager. If you really want standalone winodws (I've done that in the past to double check some behavior) then you'll need to change some things in `editor.cpp` to disable the reparenting, focus handling, and `Editor::fix_local_coordinates()`, and to resize the `win32_window` in `Editor::resize()`.
