### ISSUE TITLE
Gentoo: yabridge build failed with system bitsery without bitsery.pc file

### ISSUE THREAD

**Issue by Yann-Kaelig** [robbert-vdh/yabridge#18]
Hello,

devs, musicians, dev/musician and musician/dev :)
First I would like to thanks about your work. 
About me, I'm musician, advanced linux user, I like packaging but I do not consider myself as a dev even if I have some knowledge on the subject.

I use gentoo for my daily work, and I thought it would be nice to create an ebuild for yabridge and share it with other musicans.

You will find my work here https://framagit.org/architekt/proaudio-overlay/-/tree/master/media-libs/yabridge

**Problem description**
First of all you have to know that the use of subproject is disabled by default on Gentoo with meson. This is why I had to create an ebuild for bitsery available here https://framagit.org/architekt/proaudio-overlay/-/tree/master/dev-libs/bitsery
 
Next I patched the meson.ebuild file as you can see here https://framagit.org/architekt/proaudio-overlay/-/blob/master/media-libs/yabridge/files/0001-disable-static-link_use-gentoo-bitsery-deps.patch , so that the configuration will try to find first bitsery on my system.
I realized I was missing a bitsery.pc file, and bitsery doesn't come with a .pc file, so I decided to create it manually.

> prefix=/usr
> exec_prefix=${prefix}
> libdir=${exec_prefix}/lib64
> includedir=${prefix}/include
> 
> Name: bitsery
> Description: Header only C++ binary serialization library
> Version: 5.0.3
> Cflags: -I${includedir}

The first idea that came to my mind was to modify bitsery so he will be able to create a bitsery.pc file. But later I thought it was certainly possible to modify yabridge meson.build file so that he can find the bitsery headers files. I spent a lot of time on this without any success. 
 
**What did you expect to happen?**
yabridge can build with system bitsery without the bitsery.pc file.

**What actually happened?**
yabridge failed to build with system bitsery when there is no bitsery.pc file

**System information**
Operating System: Gentoo Linux 
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.4.32
OS Type: 64-bit
Processors: 2 × AMD Phenom(tm) II X2 550 Processor
Memory: 11.7 GiB of RAM

**Debug log**
[meson-log.txt](https://github.com/robbert-vdh/yabridge/files/4650128/meson-log.txt)

**Other**
Could you plz help me?
Thank you

**Comment by robbert-vdh** [comment]
First of all, thanks for giving yabridge a shot! I've never actually used Gentoo myself, so we'll have to figure this out together haha. I went with the subproject only approach since I didn't expect any system to have bitsery available in the repositories and mixing versions could potentially cause some hard to grok template error messages. I also did not know that there were distros out there that disabled the dependency fallback/subproject mechanism of Meson! What do you think would be a good solution? I can think of:

1. Manually adding a pkgconf file like the one you added above. This would probably be the cleanest solution. You can use the `PKG_CONFIG_PATH` environment variable to tell pkgconf to an additional directory for `.pc` files. You'll then have to patch these lines in the meson.build file (like you already did):

   ```patch
    # to distribute a prebuilt version of yabridge
    boost_dep = dependency('boost', version : '>=1.66', static : true)
    boost_filesystem_dep = dependency('boost', version : '>=1.66', modules : ['filesystem'], static : true)
   -bitsery_dep = subproject('bitsery').get_variable('bitsery_dep')
   +bitsery_dep = dependency('bitsery', fallback : ['bitsery', 'bitsery_dep'])
    threads_dep = dependency('threads')
   -tomlplusplus_dep = subproject('tomlplusplus').get_variable('tomlplusplus_dep')
   +tomlplusplus_dep = dependency('bitsery', fallback : ['bitsery', 'bitsery_dep'])
    # The built in threads dependency does not know how to handle winegcc
    wine_threads_dep = declare_dependency(link_args : '-lpthread')
    xcb_dep = dependency('xcb')
   ```

   So if bitsery is not already available as a package in Gentoo, then you could download a copy locally, create a `bitsery.pc` file based on the one you posted but with `prefix` pointing to the just downloaded copy of bitsery (are relative paths in pkgconf a thing?), and then run meson with the `PKG_CONFIG_PATH=<path_to_directory_containing_bitsery.pc>` environment variable set.
2. Patch the meson.build file to replace the current definition of `bistery_dep` with an include of the header files:

   ```meson
   bitsery_dep = declare_dependency(include_directories : include_directories('<some path to bitsery\'s include/ directory>'))
   ```

   Since that's all the Meson wrap is doing. This approach won't work with the new toml++ library I will be adding in the next version though (see below).
3. Use the regular version of Meson without the subproject/fallback dependency restrictions from pip to build yabridge. This would be the simplest and cleanest solution, but of course that kind of goes against the whole idea of Gentoo and ebuilds.

In the output you posted it looks like Meson finds bitsery's CMakeLists.txt file and then somehow fails, but it's not picking up the pkgconfig file. SInce you tried going with that approach first, what went wrong there? Is the `bitsery.pc` file you posted installed to either `/usr/lib64/pkgconfig` or `/usr/share/pkgconfig` and are bitsery's headers located in `/usr/include/bitsery`? At least that's where Meson was searching for those files.

It may also be good to know that I'm currently working on adding the ability to host multiple plugins within a single process, and that uses the [tomlplusplus](https://github.com/marzer/tomlplusplus) headers only library through another Meson subproject. Luckily that library also uses Meson and thus already comes with a pkgconfig file, so that should probably be easy once we figure this out.

**Comment by Yann-Kaelig** [comment]
> In the output you posted it looks like Meson finds bitsery's CMakeLists.txt file and then somehow fails, but it's not picking up the pkgconfig file. SInce you tried going with that approach first, what went wrong there? Is the bitsery.pc file you posted installed to either /usr/lib64/pkgconfig or /usr/share/pkgconfig and are bitsery's headers located in /usr/include/bitsery? At least that's where Meson was searching for those files.

In this log, I have removed the bitsery.pc file that I manually created from the /usr/include/bitsery 

Bitsery headers are located in /usr/include/bitsery and I put my bitsery.pc file in /usr/lib64/pkgconfig/bitsery.pc while keeping my meson.ebuild patch. It may be my mistake, and with the code present in my patch he expects to have a .pc file.

For any useful purpose I make available in attached file the gentoo bitsery package. 
[bitsery-5.0.3.tbz2.zip](https://github.com/robbert-vdh/yabridge/files/4651230/bitsery-5.0.3.tbz2.zip)

I will deepen the first proposal, I tested the second but strangely it did not work, I will still try again and for the third we can just forget it :)

**Comment by robbert-vdh** [comment]
That sounds like it should work! If using subprojects is really not an option, than installing bitsery's (and in the future also tomlplusplus's) headers system wide with accompanying pkgconf files should do the trick. I can also change the meson.build file to first look for system dependencies before trying subprojects, but since you want to disable static linking Boost you'd still have to patch the meson.build anyways so that probably wouldn't be of much use.

**Comment by Yann-Kaelig** [comment]
Well

I chose to go with your first proposal, also my first idea and as we say the first idea is always the best, but since I don't do things by halves I decided to patch bitsery.
Now bitsery installation provide a bitsery.pc file.
You can see the patch here https://framagit.org/architekt/proaudio-overlay/-/blob/master/dev-libs/bitsery/files/0001-create-install-pkgconfig-file.patch

I leave you the last word and the pleasure of closing this issue :)

Thx you very much for your help

**Comment by robbert-vdh** [comment]
Great to see that you've figured it out! Next challenge would be adding multilib support to the ebuild for the bitbridge, but that should only be a matter of adding the extra dependencies for the 32-bit boost libraries and libxcb. Let me know if you run into any issues with yabridge!
