### ISSUE TITLE
Softube plugins showing blank screen after upgrading to Wine 7.10

### ISSUE THREAD

**Issue by jarkkojs** [robbert-vdh/yabridge#184]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

This is not probably a yabridgectl issue but after upgrading from Wine 7.8 to 7.10, all the Softube plugins show just blank screen instead of the user interface. Downgrading to 7.8 makes things work again.

Note: I have not tried VST2 versions yet. I think I'll check that at some point.

### What did you expect to happen?

-

### What actually happened?

-

### Operating system

Arch Linux

### How did you install yabridge?

https://aur.chaotic.cx/

### yabridge version

4.0.1

### yabridgectl version

4.0.1

### Wine version

`wine-tkg-staging-fsync-git 7.10.r0.g94f00cd9-327`

### Plugin

Any Softube plugin

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.2

### Desktop environment or WM

Xfce 4.16

### GPU model

NVIDIA RTX 2070

### GPU drivers and kernel

`mesa 22.1.1-2`, `linux-zen 5.18.3.zen1-1`

### Debug log

-

### Anything else?

-

**Comment by robbert-vdh** [comment]
Closing this since this is a Wine issue and there hasn't been a response in a couple months.

**Comment by avanzzzi** [comment]
@robbert-vdh It's closed but I'll comment here as I'll keep trying to figure this out and at least there's a way to still use the plugins and since Softube just released an Official ENGL suite, some might look into it.

I'm using wine-tkg 8.19 in my path but I'm keeping a 7.0 wine-tkg here so when I need Softube plugins I'll just use:

```WINELOADER=~/.local/share/wine-7.0-staging-tkg-amd64/bin/wine carla-single vst3 ~/.vst3/yabridge/SoftubePlugin.vst3```

And then I'll use Jack connect/graph to make it work with the other plugins/DAW running in a different wine/wineserver.

Unfortunately, wine doesn't show any error when it doesn't work. The output is identical, UI simply doesn't show up. I tried with different prefixes with and without dxvk and with opengl disabled in the plugin. The newer builds (9.x) doesn't work too.

**Comment by notaz** [comment]
Wine bug: https://bugs.winehq.org/show_bug.cgi?id=56935
If you are building your own wine you can just revert f397807415b4807aeabac7243a13a15599008ee7 and it will work again.
