### ISSUE TITLE
Support CLAP plugins

### ISSUE THREAD

**Issue by dehuszar** [robbert-vdh/yabridge#190]
### Feature description

I just took advantage of the new offer from AudioThings who released their Wires plugin with CLAP support.  Unfortunately, they don't support Linux.  I will ask them separately to do so, but now that the CLAP format exists, and there will be several Windows-only plugins that use CLAP, I would love to see yabridge similarly set up CLAP plugins as it does for VSTs

**Comment by robbert-vdh** [comment]
This is on the todo list! I was waiting for some more Windows-only CLAP plugins, but after personally seeing Limitless get ported to CLAP in a couple hours a couple weeks ago I think this will happen sooner rather than later. It will probably still be a little while though, as I'm also working on some other CLAP related projects right now (I have this [plugin framework](https://github.com/robbert-vdh/nih-plug)/plugin suite, and I just started working on a [CLAP validator](https://github.com/robbert-vdh/clapval)), and I'll also be going on vacation in a couple weeks. But after I'm back I'll definitely start working on this.I'm not really looking forward to either writing out all of the boilerplate for serializing, logging, and handling all of the extension functions, or writing some tool to automate that for me. But other than having to get through the boring boilerplate work it won't be very difficult to implement.

**Comment by robbert-vdh** [comment]
By the way, small status update from yesterday:

https://user-images.githubusercontent.com/748520/193574235-1867a8c2-f6db-405e-8c1f-dd97287f5100.mp4

Notice how smooth the window resizes are with CLAP bridging. This is also a 32-bit CLAP plugin, because why not.

**Comment by robbert-vdh** [comment]
It will probably still take another couple months of work to get it into a releasable state, but I just merged the `feature/clap` branch into `master`. There's still a ton of basic stuff missing so don't get too excited just yet, but it at least sort of works and this makes it a lot easier to keep documentation and things up to date without having to rebase readmes all the time.

**Comment by 38github** [comment]
Thank you for your dedication!

**Comment by wcvb** [comment]
I second that :)

**Comment by robbert-vdh** [comment]
Oh heh, completely forgot to close this issue with yabridge 5.0. Thanks for the reminder!
