### ISSUE TITLE
IK MULTIMEDIA plugins crash when hitting play Mixbus6

### ISSUE THREAD

**Issue by durutti** [robbert-vdh/yabridge#21]
Hello, nice work,
I have an issue with IK Multimedia plugins. The plugins are found on Mixbus I can open the gui
but when I hit play Mixbus6 crashes. I am using the copy method by adding the lines suggested
in .bashrc and .profile
I am also attaching the log and the output form Mixbus6 started form terminal

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/4799431/yabridge.log)
[Mixbus6.txt](https://github.com/robbert-vdh/yabridge/files/4799554/Mixbus6.txt)
Thank you for your work

**Comment by robbert-vdh** [comment]
Hi!

Thanks for the report. The logs didn't show anything weird other than that the suspicious 'malloc(): memory corruption', so I briefly checked out the demo of TR5 Tape Machine 24 and I discovered:

- That there are no issues when using Carla or Bitwig Studio.
- Loading the plugin in Mixbus6 or Ardour 6 (which Mixbus6 is based on) either works fine, or hangs the Wine process on `effEditOpen()` (so when the plugin editor window is supposed to open). I can't seem to find the pattern here, and 95% of the times times the GUI opens just fine.
- The crash on play happens in Mixbus6, but not in Ardour.

So after taking a closer look I found out that Mixbus was sending a 138 sample sized buffer when starting playback instead of using the normal buffer size. This lead me to an incredibly dumb memory error caused by careless copy and pasting that I'm super surprised has not caused any issues before this, since it has been part of yabridge since the very start.

I've just fixed the issue on the master branch. Could you try and see whether this also solves the issue for you? You can grab a prebuilt version on the [automated builds](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) page.

**Comment by durutti** [comment]
wow that was fast, I wiil try it and report back.
Thank you

**Comment by robbert-vdh** [comment]
And regarding that editor opening issue I was talking about, that's pretty weird. If you save and reopen a project where this was an issue then it's 100% reproducible, but it's still a fairly low chance of it happening in the first place. I'm not sure whether this is caused by concurrency issues on our side, or if it's the plugin or part of Wine itself that's misbehaving.

**Comment by durutti** [comment]
> And regarding that editor opening issue I was talking about, that's pretty weird. If you save and reopen a project where this was an issue then it's 100% reproducible, but it's still a fairly low chance of it happening in the first place. I'm not sure whether this is caused by concurrency issues on our side, or if it's the plugin or part of Wine itself that's misbehaving.


I have also other things to report but maybe I will open a new thread, lets see if the new commt solves for me the issu

**Comment by robbert-vdh** [comment]
Please do open another issue if you ran into more problems!

**Comment by durutti** [comment]
Ok tested the new build on both Ardour6 and Mixbus6. The commit solved the issue but
I cannot open two diffrent plugins similar to https://github.com/robbert-vdh/yabridge/issues/11
![Screenshot from 2020-06-18 20-36-03](https://user-images.githubusercontent.com/25441390/85053987-0d0e1100-b1a4-11ea-887f-0ccbf069e5b3.png)

my .bashrc has the follwing lines
yabridge_home=$HOME/.local/share/yabridge
plugin_dir_IK="$HOME/.wineIK/drive_c/Program Files/VstPlugIns"

find "$plugin_dir_IK" -type f -iname '*.dll' -print0 |
  xargs -0 -P$(nproc) -I{} bash -c "(winedump -j export '{}' | grep -qE 'VSTPluginMain|main|main_plugin') && printf '{}\0'" |
  sed -z 's/\.dll$/.so/' |
  xargs -0 -n1 ln -sf "$yabridge_home/libyabridge.so"

and .profile the follwing line
export PATH="$HOME/.local/share/yabridge:$PATH"

**Comment by robbert-vdh** [comment]
Mixbus and Ardour (and anything that doesn't run every plugin in its own process) won't like those symlinks, since they are technically the same `.so` file and will thus only be loaded once and then reused. So what you'll want to do is to remove the existing symlinks (since otherwise you won't be able to create copies of libyabridge.so there) and then to create new copies instead. So with the above paths, you would want to run:

```shell
yabridge_home=$HOME/.local/share/yabridge
plugin_dir="$HOME/.wine/drive_c/Program Files/Steinberg/VstPlugins"

# To remove the old symlinks
find "$plugin_dir" -type l -iname '*.so' -delete

# To create the new copies
find "$plugin_dir" -type f -iname '*.dll' -print0 |
  xargs -0 -P$(nproc) -I{} bash -c "(winedump -j export '{}' | grep -qE 'VSTPluginMain|main|main_plugin') && printf '{}\0'" |
  sed -z 's/\.dll$/.so/' |
  xargs -0 -n1 cp "$yabridge_home/libyabridge.so"
```

And it's probably not a good idea to have that as part of your .bashrc! It won't do any harm of course, but it will cause delay opening bash because now you're iterating through all of your VST plugin every time you open a shell. At least on my system this takes a solid second because of all the Melda plugins I've got installed.

**Comment by durutti** [comment]
Ok I see my error, I thought was uisng the copy method but I was actually using the symlink one.
Thank you again, now everything works as it is supposed to. By the way which is an apropriate place to put the above commands?

**Comment by robbert-vdh** [comment]
You would just run them once if you install new plugins, and since you're using the copying installation method you'd also want to run them again when you update yabridge. So you could either just paste them from the readme whenever you need them, or you could create a shell script (in `~/.local/bin` for instance) to make it a bit more convenient.
