### ISSUE TITLE
SoundToys 5 not working on Fedora 37

### ISSUE THREAD

**Issue by Raptorneutron** [robbert-vdh/yabridge#226]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Soundtoys 5 doesn't work on my current installation, even though it works on another PC with Arch Linux. I have some logs, i'll be attaching them

### What did you expect to happen?

Open up as any other yabridge plugin

### What actually happened?

Error code on Bitwig:
`Plugin host error createAEffectInstance returned NULL`

### Operating system

Fedora 37

### How did you install yabridge?

Patrickl copr repo

### yabridge version

5.0.2

### yabridgectl version

5.0.2

### Wine version

wine-7.20.r0.gacb05462 ( TkG Staging Esync Fsync )

### Plugin

Soundtoys plugins (Crystallize, Decapitator...)

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Bitwig Studio 4.4

### Debug log

[yabridge.zip](https://github.com/robbert-vdh/yabridge/files/10298676/yabridge.zip)

**Comment by SunflowerHunter** [comment]
I have the same issue with all of the soundtoys plugins on yabridge 5.0.2, wine 7.22
I get the same type of errors: `<some number>:fixme:unwind:execute_cfa_instructions <some number>: unknown CFA opcode 2e`
[yabridgesoundtoys.log](https://github.com/robbert-vdh/yabridge/files/10300711/yabridgesoundtoys.log)

**Comment by robbert-vdh** [comment]
I only have these:

![image](https://user-images.githubusercontent.com/748520/209856282-cdfe854a-72c7-4a1a-bd1e-5badba9a8171.png)

But the latest versions of these work fine with yabridge. Tried both the VST2 and the VST3 versions in a clean Wine prefix with Wine Staging 8.0-rc2. Only issue seems to be missing text in Little AlterBoy, and that can probably be fixed by installing some additional fonts (this prefix is completely stock). And given the place where the plugin crashes in the first debug log it's either an issue with your prefix or with iLoK (related to your prefix). Try deactivating the licenses in the iLoK license manager (so you don't lose them) and then recreate the prefix from scratch. I'm not using any overrides.
