### ISSUE TITLE
yabrdige on wine 5.11

### ISSUE THREAD

**Issue by arjunkathuria** [robbert-vdh/yabridge#24]
Hi @robbert-vdh ,

i am getting this error when trying to manually run the host as asked in the docks
```
arjun@laptop:~/Downloads/yabridge-1.2.1(1)/yabridge$ wine yabridge-host.exe
002c:fixme:winediag:__wine_start_process Wine Staging 5.11 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
002c:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
0024:err:module:__wine_process_init failed to load L"Z:\\home\\arjun\\Downloads\\yabridge-1.2.1(1)\\yabridge\\yabridge-host.exe", error c000012f
arjun@laptop:~/Downloads/yabridge-1.2.1(1)/yabridge$ 0034:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
```

The answer to `__wine__process_init` errors in the docs is that you are running an older version, please upgrade your wine, but i am on the latest wine staging ? :confused:

is there anything i am missing ? i used the copying method and bitwig wont see my plugins too : /

POP_OS 20.04 (ubuntu dreivative) (5.7 liquorix kernel) if that helps? 

Edit:- 

I also compiled it from source with the wine staging headers. i get this now
```
wine yabridge-host.exe
002c:fixme:winediag:__wine_start_process Wine Staging 5.11 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0024:err:module:__wine_process_init failed to load L"Z:\\home\\arjun\\Documents\\remotes\\yabridge\\build\\yabridge-host.exe", error c000012f
```

**Comment by robbert-vdh** [comment]
Hi! Winelib applications can be a bit confusing. The file you're trying to run, `yabridge-host.exe`, is neither a Windows executable nor a winelib (i.e. an application that uses Wine as a library, like yabridge) but a small shell script generated by Wine that runs the `yabridge-host.exe.so` file adjacent to it. So to run that file manually you'd either have to run `~/Downloads/yabridge-1.2.1(1)/yabridge/yabridge-host.exe` (so without `wine`) or you could run the file directly using `wine ~/Downloads/yabridge-1.2.1(1)/yabridge/yabridge-host.exe.so`. I just confirmed that the binaries from the GitHub releases do indeed still run with Wine 5.11 (they're built with Wine 5.8 at the moment), so the problem you're facing is probably unrelated.

Since you're using Bitwig, could you install your plugins using symlinks and then post some logs if it still does not work? You'll have to make sure that you extract the downloaded archive to a safe location (you could of course keep them in your downloads directory, but it would very easy to accidentally remove them) and that the symlinks point to your copy of `libyabridge.so`. To create log files, simply start Bitwig from the command line with `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1 bitwig-studio`. After trying to scan a few plugins you'll find the log file at `/tmp/yabridge.log`.

**Comment by arjunkathuria** [comment]
running yabridge-host.exe without the wine seems to work.

but now in bitwig. all my windows vst have the error
```
com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: createAEffectInstance returned NULL
```

**Comment by robbert-vdh** [comment]
Are there no messages in the 'View plug-in errors' section in Bitwig under Settings -> Plug-ins? If so then your symlinks are incorrect. You can quickly verify that by running the following in a terminal, replacing the value of `plugin_path` with the path to a symlink you created:

```shell
plugin_path="$HOME/.wine/drive_c/Program Files/Steinberg/VstPlugins/Serum_x64.so"

readlink "$plugin_path"
readelf -s "$plugin_path" | grep yabridge
```

The `readlink` command should print the path to the copy of libyabridge.so you're using, and the last line should print a few lines related to yabridge.

**Comment by arjunkathuria** [comment]
Something really weird is happening here.

if i run `bitwig-studio` from a terminal and launch the apps then the plugins are working.
the only plugin erroring then is `` with the error

```
/home/arjun/.wine/drive_c/Program Files/Steinberg/VSTPlugins/plugin.so

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: createAEffectInstance returned NULL
-------------------------------------------------------------------
```

but if i launch bitwig form GUI. all plugins break again in the sense that they are still visible in the plugin selection menu but when you chose them, in the device menu it says "failed to load".

am i really missing something here? : / 

also i am using the copy method, not the symlink method, since i use reaper quite a lot to. 

sorry if these questions are stupid : /

**Comment by robbert-vdh** [comment]
Ah, since you're using copies then the issue is that yabridge can't find `yabridge-host.exe`. You've already added the containing directory to your `PATH` environment variable somewhere, where did you do that? You'll have to add it in some place that's read by your login shell, or else it won't bet set for GUI applications. Assuming your using Pop!_OS's default Bash shell and that you've installed yabridge to `~/.local/share/yabridge`, then you should put `export PATH="$HOME/.local/share/yabridge:$PATH"` in your `~/.bash_profile` file and then log out and back in again. After that any application should be able to find yabridge's files.

**Comment by arjunkathuria** [comment]
i added it to the path in `.bashrc` and `.zshrc`

i'll try putting it to `.profile` then.

Thanks for taking out the time to reply to this, pardon my noob-ness here.
Also, Thanks for your work on this. it's really gonna help me. when i do get i working eventuallly, heh.

Best
- Arjun

**Comment by robbert-vdh** [comment]
Bash and Zsh only read `~/.bashrc` and `~/.zshrc` for interactive sessions. During login Bash will read `~/.bash_profile` from your home directory if it exists, and `~/.profile` as a fallback if it does not. Zsh is a bit more convoluted and it has three different places where you could theoretically set the environment variable, but if you're using Zsh as your login shell (if you're not sure, run `echo $SHELL` in a terminal) then you'll want to edit `~/.zshenv` instead since that will always be executed for both login and interactive shells.

**Comment by arjunkathuria** [comment]
heh, works sweet now after putting in `~/.profile`.

you're a hero for making this plugin. i can finally NOT boot into any other os for music production now. 

Thanks a bunch : )
