### ISSUE TITLE
Some (few) T-Racks 5 Plugins not working

### ISSUE THREAD

**Issue by lentferj** [robbert-vdh/yabridge#26]
I am about to switch over from LinVST, foremost because I like your development approach far better (e.g. real, readable commits ;) ) and easier to follow. Also, stuff like resizing in Ardour/Mixbus seems to work flawless with yabridge and not really in LinVST. I have quite a few Windows plugins running with LinVST currently and I just tried them all with yabridge. Almost all seem to work (I can provide a list later on if you are interested) with the exception of Waves (I will open a separate issue for this later on) and a few IK Multimedia plugins. I have all T-Racks 5 plugins, basically, so support seems to be very good with a few exceptions that fail during scan.

These are:
TR5 Tape Machine 440.so
Philharmonik 2.so
Lurssen Mastering Console.so
TR5 Tape Machine 24.so
AmpliTube 4.so
TR5 Tape Machine 80.so
TR5 Tape Machine 99.so

I am running Debian 10 (Buster) using latest binary release of yabridge. I tried with Mixbus 6.1.1, Wine-Staging 5.8 from WineHQ.

I attached the debug log file. These plugins do work with LinVST without any major problems.

Please let me know if I can help with any further infos.

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/4944190/yabridge.log)

**Comment by lentferj** [comment]
Ha, so, after looking into this a little bit longer (reading and trying to understand the debug log :) ) this isn't an issue - all of the plugins listed above to work.
I had WINEPREFIX set to ~/.wine64 in my shell, while those plugins "live" in ~/.wine64_TrackS.
Maybe it would be a good idea, to not use the default WINEPREFIX variable to override autodetection of wine prefixes for yabridge? It seems to not unlikely people have WINEPREFIX set to some value. Maybe use a yabridge specific env variable to enable overriding of prefix auto detection?

**Comment by lentferj** [comment]
unsetting WINEPREFIX also solves the scanning problem with Waves plugins. They still can't be loaded, though. I will open another issue for that later.

**Comment by robbert-vdh** [comment]
Hi!

Yabridge respects `$WINEPREFIX` because if you have manually set this environment variable, then the expected behavior would be that everything Wine related is going to use that prefix (otherwise you would not have added an override). To make it a bit clearer that this is happening the `wine prefix:` line of the initialization message in the log reads `'/home/lentferj/.wine64 <overridden>'`, but I agree that that can be very easy to miss if you're not looking for it. If you just want to use `~/.wine64` as your default Wine prefix without using that prefix for everything, may I suggest just symlinking `~/.wine` to `~/.wine64`?

As for the Waves plugins, I actually haven't tried any yet because I didn't want to deal with the DRM, but I'm pretty sure I own Renaissance Bass so I'll give it a try to see what's up.

**Comment by lentferj** [comment]
Ok, LinVST seems to behave different in regard to wine prefixes, but your explanation makes very much sense. I will adopt my setup accordingly. I have switched to yabridge as my default now. There seem to be a few plugins here and there that do not yet behave correctly (e.g. Plugin Alliance stuff), but the vast majority seems to be working out of the box. Great work!! I will report anything I find in specific issues.
