### ISSUE TITLE
OSX support 

### ISSUE THREAD

**Issue by williamcorney** [robbert-vdh/yabridge#268]
### Feature description

Would it be possible to build this from source on Mac OSX?

I’m going to take a deep dive into reading through site to see what I can figure out myself

**Comment by williamcorney** [comment]
Any thoughts on this ?

**Comment by robbert-vdh** [comment]
You would need to reimplement the Linux-specific bits for macOS. The obvious big one being the window embedding and drag-and-drop handling in `editor.cpp` and `xdnd-proxy.cpp`. I don't know how that would work, but you'd need to find a way to reparent the XQuartz window (or does Wine use native Carbon or Cocoa windowing on macOS?) into the host's window. There are also some other Linux-specific things spread around like the way we check for open sockets and zombie processes, both of which involve procfs. I'm not going to work on this, but I can point you to the relevant bits if you want to work on this yourself.

Since there are few current commercial plugins that don't get a release on macOS though, I don't know if it would be worth the effort. And then you also need to use a host that can handle x86_64 VST2/VST3/CLAP plugins, like Bitwig can.

**Comment by williamcorney** [comment]
Many thanks @robbert-vdh .  Your reply gives me more than enough to start from .  I'll come back to this thread if need any relevant bits
