### ISSUE TITLE
PSP E27 "live" resizing does not work on BWS 3.2.6

### ISSUE THREAD

**Issue by lentferj** [robbert-vdh/yabridge#27]
PSP E27 (not "se" version) has buttons (x2, PA11) that will add extra functionality and resize the plugin gui.
When I click those buttons in MB32C v6.1.1 the gui gets resized automatically, not so on BWS 3.2.6.

Mixbus:
![image](https://user-images.githubusercontent.com/5664183/87883709-65d20300-ca09-11ea-9a64-4713667d56d1.png)

Bitwig:
![image](https://user-images.githubusercontent.com/5664183/87883728-99ad2880-ca09-11ea-8f02-8d0445438041.png)

In Bitwig I will have to close and reopen the plugin gui, then it works.

http://www.pspaudioware.com/plugins/equalizers/psp_e27/

A demo is available, but you will need to register with PSP and create an iLok account (and setup iLok using WINE). If this is too much of a hassle for you, I totally understand. If I can support in any way, please let me know. 

PS: this is a huge step from LinVST still, clicking x2 or PA11 would usually crash the plugin ;)

**Comment by robbert-vdh** [comment]
I'll see if I can get E27 installed tomorrow and then I'll give it a shot! 

Interestingly enough this is the first time I've seen this particular issue, and it's also quite interesting that it's not happening in Mixbus (and presumably it also won't happen in REAPER either). Yabridge uses the same trick LinVST uses to avoid having to use Wine's own XEmbed implementation since that doesn't work very well, and that basically involves lying to Wine about the screen coordinates of the windows, so I would not have been surprised to have seen it pop up sooner. Perhaps E27 is drawing to the parent window directly rather than to its own window? You'll probably find that the GUI will be more or less in the correct place if you move the window to the top left corner of your screen before clicking the X2 button. I'll see what I can do once I've installed E27.

**Comment by robbert-vdh** [comment]
So these PSP plugins are doing some weird things. They really seem to be drawing using their parent window's coordinates instead of their own. This is probably also why they do render properly when using a host that embeds plugin editor windows inside of another window such as Ardour/Mixbus, and also when not embedding the Wine window at all and just leaving it as is. Also in REAPER they either don't render (when using bridging) or they cause a segfault within REAPER itself after opening the editor.

I did come up with a workaround that fixes the issue, but it does introduce a few other subtle issues in the process (which would also be solvable, but just layering hacks doesn't sound like the best idea). [This patch](https://hastebin.com/zejuzayiyu.patch) fixes the issue for PSPaudioware plugins, but it also causes newly opened plugins to steal focus resulting in the next click outside of the window ignored.

Since this issue appears to be isolated to PSPaudioware plugins, I think the most sensible approach would be to add a plugin-specific setting (through [yabridge.toml](https://github.com/robbert-vdh/yabridge/tree/master#plugin-groups)). That setting would either cause the editor window to be embedded inside of yet another window (like what Ardour and Mixbus are doing), or it would use Wine's XEmbed implementation instead of our own reparenting method (but the last time I tried that it didn't like resizing windows at all and it had some redrawing issues, which is the whole reason why yabridge is doing its own thing anyway).

I'll have to investigate some more to see what would work best here!

**Comment by cameronleger** [comment]
Plugin-specific settings like this sound amazing! I really hate the approach of compiling different versions with different settings to get them all-xembed or similar ;) I don't have this problem but I figured I'd chime in on that.

**Comment by robbert-vdh** [comment]
Sorry for taking so long! I've ended up adding an [option](https://github.com/robbert-vdh/yabridge#editor-hosting-modes) that causes the plugin's editor to be embedded inside of a child window of the Wine window we'd normally use. This sounded like both the simplest and least hacky way to solve the issue. I have not yet noticed any weird behaviour from having this option enabled for all plugins, but I've left it disabled by default to limit the amount of moving parts and because so far it only really seems be necessary for some of these PSPaudioware plugins.

If you want to give it a shot, then you can download a prebuilt version from the [automated builds](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22) page or you can use the [yabridge-git](https://aur.archlinux.org/packages/yabridge-git/) AUR package if you're running Arch or Manjaro. You'll have to create a `yabridge.toml` file and then set the `editor_double_embed` option for your PSPaudioware plugins. There's an [example configuration file](https://github.com/robbert-vdh/yabridge#example) in the readme that you can more or less copy and paste.

**Comment by robbert-vdh** [comment]
I've released [yabridge 1.4.0](https://github.com/robbert-vdh/yabridge/releases) with the above mentioned embedding option. Please reopen this issue if this does not fix the problem for you, or if you came up with a better solution!

**Comment by lentferj** [comment]
Sorry for coming back so late. First off - thank you very much for this quick fix. It works - almost for me ;).
When you click X2 on a newly loaded plugin in BWS, it's fine - resizing works, same for just PA11, but x2 and then PA11 breaks it again.
Anyway - it's "good enough" for me. I use PSP plugins mainly in Mixbus, and they do not cause problems there.

x2 is fine:
![grafik](https://user-images.githubusercontent.com/5664183/88568511-64bc5980-d039-11ea-9a39-19b8da80985e.png)

PA11 is fine, too:
![grafik](https://user-images.githubusercontent.com/5664183/88568764-c1b80f80-d039-11ea-968e-03b6af71ccd7.png)

x2 AFTER PA11, too:
![grafik](https://user-images.githubusercontent.com/5664183/88568842-dd231a80-d039-11ea-9142-293224daac55.png)

x2 then PA11 not so much:
![grafik](https://user-images.githubusercontent.com/5664183/88568931-fdeb7000-d039-11ea-9fc4-c57c02e63bf5.png)

**Comment by robbert-vdh** [comment]
Strange! I can't reproduce that with E27 1.6.2, [this](https://github.com/nine7nine/pkgbuilds_nspa/tree/master/wine-nspa) modified build of Wine Staging 5.9 (but I also can't remember it being an issue with regular Wine Staging 5.13), Bitwig Studio 3.2.6 and KDE Plasma 5.19.3. All combinations of x2 and pa11 resize the window just fine for me. Looks like either the plugin is not sending `audioMasterSizeWindow`, Bitwig is not resizing the window, or the window manager is somehow just not feeling it.

**Comment by lentferj** [comment]
I am on Debian 10/LXDE with wine-staging 5.8 from winehq.org.
But, really - it's fine for me the way it is. Seems to much effort for a minor problem.

**Comment by robbert-vdh** [comment]
As a bit of extra background info as to what's happening here, the actual window is controlled by the host (so Bitwig Studio in this case). The host queries the size of the window once when opening the editor, and it will resize the window whenever the plugin calls `audioMasterSizeWindow()`. So the problem here is either Bitwig not properly resizing the window, the window manager somehow preventing the resize or the plugin not sending the event.
