### ISSUE TITLE
REAPER freezes

### ISSUE THREAD

**Issue by lyonelz96** [robbert-vdh/yabridge#29]
**Problem description**
  - REAPER recognizes the plugins fine but when I try to add them to the track REAPER either freezes and just becomes unresponsive or the UI loads and then it freezes.
 
**System information**
- Operating system: Arch
- Wine version: wine-5.14 (Staging)
- Installation method: AUR package, yabridge-bin
- yabridge version: 1.4.1
- yabridgectl version: 1.4.1
- REAPER version: 6.13

**Debug log**

#### Archetype Plini
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5044639/yabridge.log)

#### Spitfire BBCSO Discover
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5044640/yabridge.log)

#### Spitfire LABS
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5044642/yabridge.log)

All of the above plugins work using LinVST, I just wanted to see if I got a bit of a better performance with your program! I also noticed in your README the section on the audio specific Wine version, I will definitely be checking that out. Nevertheless great work!!

**Comment by robbert-vdh** [comment]
I'm away from my desktop for a few days so I can't check for myself just yet, but from the looks of it REAPER doesn't properly handle the `audioMasterUpdateDisplay` callback. This issue is not present with LinVST because it silently ignores that function call and others like it. From my limited experience REAPER's plugin hosting can be a bit hit or miss (as in, plugins that work fine in any other VST host sometimes have issues in REAPER). I did have some success messing around with REAPER's plugin bridge settings, so maybe that's something you can try!

Oh and on an unrelated note just in case it was not intentional, the Wine prefix is overridden to `/home/lyonelz/Wine/Audio` through the `WINEPREFIX` environment variable so every plugin will be loaded using that Wine prefix.

**Comment by lyonelz96** [comment]
I'll take a look at the plugin bridge settings! The Wine prefix being overridden is intentional.

**Comment by robbert-vdh** [comment]
I did some digging around and I'm at least 95% sure this is a bug in REAPER's plugin GUI handling on Linux.  It seems to come down to a timing issue, where REAPER freezes immediately when it receives `audioMasterUpdateDisplay` while it is calling `effGetProgram` as part of its UI updating routine. If I modify yabridge to also periodically call this function from a plugin that would otherwise run just fine under REAPER (such as OTT, which doesn't use  `audioMasterUpdateDisplay` itself) then this also causes it to freeze. I assume the people over at Cockos made sure the Linux version works with properly with most native Linux VST plugins, and since those plugins probably don't use `audioMasterUpdateDisplay` they never ran into the issue themselves. This might be worth sending a bug report over.

**Comment by robbert-vdh** [comment]
I've added an option as a temporary workaround until this is fixed in REAPER. This is not ideal, but I think it's the best compromise at the moment and this will still allow you to use REAPER's regular non-bridged plugin hosting mode since REAPER's editor resizing seems to be broken when using their plugin bridges. See [this comment](https://github.com/robbert-vdh/yabridge/issues/32#issuecomment-674899066) in #32 for more information.

**Comment by lyonelz96** [comment]
Awesome! 
Adding the config file in the VST folder did the trick. I'll leave it up to you if you wanna close the issue or not.

**Comment by robbert-vdh** [comment]
That great to hear! Yeah it might be a good idea to keep this issue open for visibility's sake until it gets fixed on REAPER's side.

**Comment by robbert-vdh** [comment]
Good news, this workaround will soon no longer be needed! I've been working on a complete rewrite of yabridge's communication model on the master branch that solves this issue and issues with many other similar situations that typical VST bridges would struggle with. Event handling is now fully concurrent and yabridge will spawn additional threads as needed to process the requests, so deadlocks or blocked event loops are no longer an issue. This also translates to better performance when scanning and opening plugins as well as many other subtle improvements. There's an in-progress changelog with all changes in the new version [here](https://github.com/robbert-vdh/yabridge/blob/master/CHANGELOG.md). I still need to do some final cleanup and refactoring work, but I've been using it for the last week and it's been working great. Plugin groups are also rock solid now and can handle dozens of plugins without issues.

**Comment by lyonelz96** [comment]
> Good news, this workaround will soon no longer be needed! I've been working on a complete rewrite of yabridge's communication model on the master branch that solves this issue and issues with many other similar situations that typical VST bridges would struggle with. Event handling is now fully concurrent and yabridge will spawn additional threads as needed to process the requests, so deadlocks or blocked event loops are no longer an issue. This also translates to better performance when scanning and opening plugins as well as many other subtle improvements. There's an in-progress changelog with all changes in the new version [here](https://github.com/robbert-vdh/yabridge/blob/master/CHANGELOG.md). I still need to do some final cleanup and refactoring work, but I've been using it for the last week and it's been working great. Plugin groups are also rock solid now and can handle dozens of plugins without issues.

That is fantastic news! Can't wait to try it. Thanks for the amazing work and effort my man!

**Comment by robbert-vdh** [comment]
This is now fixed as of [yabridge 2.0.0](https://github.com/robbert-vdh/yabridge/releases/tag/2.0.0)! :tada: 

The old workaround options has been removed since it's no longer needed.
