### ISSUE TITLE
Alternative Linking Support

### ISSUE THREAD

**Issue by cameronleger** [robbert-vdh/yabridge#3]
I understand that I have a slightly different workflow that what you've described for this plugin, but it has worked for me with LinVST and Airwave so I was expecting it to work here.

* Multiple Wine-Prefixes across drives
* Bridging .so copied next to each file in their original location
* That copy is sym-linked to a common local directory

The previous solutions handled that without a problem. Here's what happens with yabridge.

```
Renoise LOG> Audio Plugins: Searching for VST plugins in '/home/cameron/.local/share/yabridge/'
Renoise LOG> VstPlugs: Trying to instantiate /home/cameron/.local/share/yabridge/Scaler_x64.so
Error during initialization:
'/home/cameron/.local/share/yabridge/Scaler_x64.dll' does not exist, make sure to rename 'libyabridge.so' to match a VST plugin .dll file.
Renoise LOG> VstPlugs: Instantiate FAILED (MagicMatch) !!!
```

```
~/.local/share/yabridge 
Scaler_x64.so -> /mnt/...etc.../VstPlugins/Scaler_x64.so
```

**Comment by robbert-vdh** [comment]
That's another setup I hadn't thought of. It's actually also possible to use a symlink the actual .dll file. I've added support for your symlink method in ad03d870ee4a0e4286ec508c79a45c136ac535d7! Since you're using Renoise, there's also #1 that would prevent Renoise from working. I'll implement that either today or tomorrow and I will let you know when it's ready.

**Comment by cameronleger** [comment]
Actually I use Bitwig :) but it's easier to get logging output for Renoise, so I keep that around for this. I really appreciate the debugging/logging abilities in this project.

I specifically wanted to try Scaler first since there's been a bug, likely introduced somewhere in Bitwig 2.5+, where WINE-based plugins that alter MIDI for the Output crash the whole setup immediately on any change. Those plugins continue to work in Renoise, Ardour, Reaper, etc. so it's very specific to Bitwig. It even doesn't work to put the offending plugins into another wrapper plugin, like Carla! I figured I could get to the bottom of that with this project.

**Comment by robbert-vdh** [comment]
Do you know if that also happens with Bitwig running under Windows? If not then it should probably probably be easy to support it in yabridge. There's no handling for plugin -> host MIDI events right now (I kind of forgot that that was a thing), but since all the data handling has already been implemented for the regular MIDI events supporting that should be as easy as just telling yabridge that it should be reading that as MIDI data for those particular events.

**Comment by cameronleger** [comment]
It's specific to Plugins that either alter or perhaps just re-emit MIDI events, Bitwig, and having the Plugin run through any WINE Bridge that I've tried. In other words, Linux-based VSTs on Linux work, Windows-based VSTs on Windows work, but Windows-based VSTs on Linux do not work.

I ended up writing my own Plugin like Scaler but more tailored to what I want, since any Windows VSTs that change the MIDI events will crash; Cthulu, Scaler, Chorder, etc.

**Comment by robbert-vdh** [comment]
I'm pretty sure that there's no reason why it would not work under Wine. I've created an issue for it under #5. I'll get to it after I've finished getting compilation on Ubuntu 18.04 to work!

**Comment by cameronleger** [comment]
You and me, both, man! I'll gladly help on that topic since it's been bugging me for so long and I'm familiar with Plugin + Host code. Also, I'd love if you had a donation link; you deserve it!

**Comment by cameronleger** [comment]
AFAIK the recent few commits have completely resolved this :) still am curious about a donation link!
