### ISSUE TITLE
[SOLVED] wine-5.15: cannot find yabridge-host-exe.so

### ISSUE THREAD

**Issue by vlur** [robbert-vdh/yabridge#30]
Wine returns an error when running `yabridgectl sync` saying it can't run `yabridge-host.exe`:

```
-> % yabridgectl list
/home/vlur/.wine/drive_c/Program Files/Steinberg/VstPlugins

-> % yabridgectl sync
Using '/home/vlur/.local/share/yabridge/libyabridge.so'

Finished setting up 1 plugins using copies, skipped 0 non-plugin .dll files

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error: 
    
    wine: cannot find L"/home/vlur/.local/share/yabridge/yabridge-host.exe.so"
    
    This can happen when using a version of Wine that is much older than the version that has been used to compile yabridge with. Your current Wine version is '5.15'. See the troubleshooting section of the readme for more
    information on how to upgrade your installation of Wine.
    
    https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues

-> % ll /home/vlur/.local/share/yabridge/
total 6.0M
-rw-r--r-- 1 vlur vlur  8.3K Jul 27 09:40 CHANGELOG.md
-rw-r--r-- 1 vlur vlur   24K Jul 27 09:40 README.md
-rwxr-xr-x 1 vlur vlur  1.2M Jul 27 09:40 libyabridge.so
-rwxr-xr-x 1 vlur vlur   709 Jul 27 09:40 yabridge-group-32.exe
-rwxr-xr-x 1 vlur vlur  1.4M Jul 27 09:40 yabridge-group-32.exe.so
-rwxr-xr-x 1 vlur vlur   706 Jul 27 09:40 yabridge-group.exe
-rwxr-xr-x 1 vlur vlur  1.4M Jul 27 09:40 yabridge-group.exe.so
-rwxr-xr-x 1 vlur vlur   708 Jul 27 09:40 yabridge-host-32.exe
-rwxr-xr-x 1 vlur vlur 1022K Jul 27 09:40 yabridge-host-32.exe.so
-rwxr-xr-x 1 vlur vlur   705 Jul 27 09:40 yabridge-host.exe
-rwxr-xr-x 1 vlur vlur  1.1M Jul 27 09:40 yabridge-host.exe.so
```

The problem persists even after issuing `wineserver -k`.  I followed the "Automatic setup" and "Search path setup" instructions in the readme. `$HOME/.local/share/yabridge` has been added to my zsh $PATH in ~/.zshenv, ~/.zshrc and ~/.zprofile.

**System information**
- Operating system: Void Linux 5.7.15_1
- Wine version: wine-5.15
- Installation method: copies, yabridgectl
- yabridge version: 1.4.1
- yabridgectl version: yabridgectl 1.4.1

**Comment by robbert-vdh** [comment]
That's strange! What happens when you run `~/.local/share/yabridge/yabridge-host.exe` directly (so just that command, without `wine` in front of it? And what happens if you run `wine ~/.local/share/yabridge/yabridge-host.exe.so`? Does Void include some kind of hardening patches in the standard Wine Staging package? That's the only thing I can think of, since the file clearly exists and is executable.

**Comment by vlur** [comment]
I agree it's quite perplexing.

```
-> % ~/.local/share/yabridge/yabridge-host.exe
wine: cannot find L"/home/luke/.local/share/yabridge/yabridge-host.exe.so"

-> % wine ~/.local/share/yabridge/yabridge-host.exe.so
wine: cannot find L"/home/luke/.local/share/yabridge/yabridge-host.exe.so"
```
I don't know if Void does anything special with the Wine packages, but my guess would be "no" - Void as a distro usually ships only vanilla packages. Maybe I have something misconfigured with my Wine installation? (Wine is always a pain, in my experience.) That said, I'm not sure where or what to check. I am able to run other things with Wine which I use on a daily basis, e.g. foobar2000 music player.

Output of the Void package manager xbps, which says I have the latest available version installed:

```
-> % xbps-query wine   
architecture: x86_64
automatic-install: yes
filename-sha256: 457817d9ada0ce5507866a43b5c94c6630853699f57adb23dd6054986a58fecf
filename-size: 249KB
homepage: http://www.winehq.org/
install-date: 2020-08-16 01:42 CDT
installed_size: 585KB
license: LGPL-2.1-or-later
maintainer: Helmut Pozimski <helmut@pozimski.eu>
metafile-sha256: b89f520d208ac7c56a70e77e81851afcf4de331c10ffebe8230e684416305d16
pkgname: wine
pkgver: wine-5.15_1
repository: https://alpha.de.repo.voidlinux.org/current
run_depends:
	wine-common>=5.15_1
	libwine-5.15_1
	glibc>=2.29_1
shlib-requires:
	libwine.so.1
	libpthread.so.0
	libdl.so.2
	libc.so.6
short_desc: Run Microsoft Windows applications
source-revisions: wine:5719db24e5
state: installed
```

**Comment by robbert-vdh** [comment]
I've never seen this before. One potential clue could be in the way Wine is showing the path to the file it cannot find. Wine uses regular C-style `char*` strings from native paths, and `wchar_t*` wide strings for Windows paths. When Wine prints a wide string it prefixes them with `L"`, which is also what's happening in the error messages you're getting. For reference, this is what happens when Wine can't find a file on my system:

```shell
❯ wine /does/not/exist.exe
fsync: up and running.
wine: cannot find '/does/not/exist.exe'
```

Usually Wine maps the filesystem root `/` to the `Z:` drive so applications running within Wine have access to the entire file system. Maybe something went wrong there? Since the defaults should be correct you can quickly check if this is the case by temporarily renaming your `~/.wine` directory and running `~/.local/share/yabridge/yabridge-host.exe` again. If that did fix it then the drive mapping in wine (`Drives` tab in `winecfg`) of your Wine prefix was somehow messed up. If that did not fix the issue, then there's probably something wrong with the Wine package. I just checked with Arch's Wine Staging 5.15 package on Manjaro and there are no issues here.

**Comment by vlur** [comment]
Looks like you were correct about my drive mappings being messed up - I checked `winecfg` and the Z:\ drive didn't even exist. So, I did as you suggested and renamed my `~/.wine` temporarily. Wine rebuilt itself and the yabridge error vanished. I copied over my drive_c folders from the renamed wine directory and now things seem to be working as expected - Linux native REAPER sees the plugins I put in the yabridge directory and synced with `yabridgectl sync`.

I still have to do other things to see whether yabridge will work in my DAWs, but this fixed the issue in the OP. Thanks for the help and the quick responses.
