### ISSUE TITLE
Authentication popup crashes plugin

### ISSUE THREAD

**Issue by hardyharz3n** [robbert-vdh/yabridge#36]
I bought a bundle of plugins from 'Black Rooster Audio', happy that they required no pesky iLok but serials instead. While yabridge loads them just fine and one is received by their GUI overlayed with a lock icon, clicking it – which should prompt the entry of a serial via a popup window as tested in native Windows – sadly crashes the entire affair.

If I were to guess, I'd say it's got something to do with some obscure Windows service not being implemented properly in Wine, but seeing as you are miles deeper in the matter than I am, I figured asking for your opinion wouldn't hurt.

I attached the backtrace Wine spits out. Running arch with current Wine.

Thanks for reading, and most of all thanks for yabridge. It's awesome!

[backtrace.txt](https://github.com/robbert-vdh/yabridge/files/5261263/backtrace.txt)

**Comment by robbert-vdh** [comment]
Hi!

The plugin crashed somewhere internally, but given the Wine backtrace there's probably an error printed somewhere in a terminal. Normally you could use that and yabridge's [debug logs](https://github.com/robbert-vdh/yabridge#debugging) to figure out what's going on, but I just downloaded the plugins and they seem to work just fine for me on a clean Wine prefix (or at least, clicking on VEQ-5's plugin window opens up the license window as you'd expect, I don't have a license so I haven't gotten any further than that). I briefly tested the plugins with both [this](https://github.com/nine7nine/pkgbuilds_nspa/tree/master/wine-nspa) Wine Staging 5.9 fork and with vanilla Wine Staging 5.17, so the issue you're facing is almost certainly caused by some override in your Wine prefix acting up! So you could either figure out which override is causing the issue, or you could just install the plugins into a separate Wine prefix.

**Comment by hardyharz3n** [comment]
Thanks for the quick response! Having quite a few overrides in my default WP of which at least some are required for various plugins, I went ahead and set up a clean WP (with default config). Alas, there I encountered the exact same (mis-)behavior. The debug log yielded nothing new: unhandled exception, starting debugger, stacktrace dump. Seems like I'm SOL, then...oh well.

Still thanks a lot for your time, and have a nice day!

**Comment by robbert-vdh** [comment]
The plugins should work perfectly fine. Could you upload a debug log of one of those plugins installed on a clean Wine prefix?

1. First make sure that there are no leftover Wine processes left running in the
   background using `wineserver -k`.
2. Launch your host from a terminal using
   `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2 <host>`,
   e.g. `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2 bitwig-studio`.
3. Try to scan or load the plugin that's causing issues.
4. `/tmp/yabridge.log` should now contain a debug log. You can either attach
   this log directly to the issue by dragging the file onto this text box, or
   you could upload the contents to a website like GitHub's Gists or Hastebin.

**Comment by hardyharz3n** [comment]
Sure thing. Here it is:

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5262532/yabridge.log)

**Comment by hardyharz3n** [comment]
Seems like just before the exception, a series of "dwarf_get_ptr unsupported encoding" occurs. Might have to do with more than Wine, but window managers and display servers. I'm using awesome-wm and xorg, for example...

**Comment by robbert-vdh** [comment]
Interestingly enough the installer doesn't create any files in `<prefix>/drive_c/Program Files/Steinberg/VstPlugins/Black Rooster Audio` for me (I downloaded the Black Rooster Plugin Pack 2.5.1 from their website), so I've tested using the files in files in `<prefix>/drive_c/Program Files/Black Rooster Audio/Plug-Ins/*/Contents/x64` instead (those are also VST2 plugins). Maybe those also work  for you? I also saw that you're using the non-staging version of Wine 5.17, have you tried with Wine Staging? And lastly, Wine's Direct2D implementation is complaining that it can't create textures, is there perhaps something wrong with your GPU drivers? I'm not seeing any errors like that here.

**Comment by hardyharz3n** [comment]
It was some special 'stay home' bundle purchased a few months ago. Tried the others, but same phenomenon. Looks like installing wine-staging would require wine to be removed entirely, including all the plug-ins that do work – so maybe another time. Seeing how the crash certainly has to do with gfx, I'll look into that first, as I actually did mess around with my xorg some time ago. In the meantime, it's not like I depend on the BRA plug-ins, they would just be nice to have. I am very, very grateful for yabridge as well as the time you took to look into my problem here. More power to you!!

**Comment by robbert-vdh** [comment]
Switching to Wine Staging on Arch is as simple as running `sudo pacman -S wine-staging` and replacing the package, no need to remove any files from your home directory! But the plugins (I was using `<prefix>/drive_c/Program Files/Black Rooster Audio/Plug-Ins/VEQ-5.bundle/Contents/x64/VEQ-5.dll`) also work fine for me with plain old Wine, although it's still a good idea to use Wine Staging since it includes lots of additional patches and I've never encountered something that didn't work with Wine Staging that did work with regular Wine.

**Comment by hardyharz3n** [comment]
Oh! Well then, I switched to wine-staging, and it turned out that the overrides I had have become obsolete. 1:0 for a bit of order! The BRAs remain on strike, however, and I don't quite know how to debug the D2D stuff – all I know is that any other 2D-gfx (seem to) run perfectly fine under Wine. I'll just make do without them!

**Comment by robbert-vdh** [comment]
Have you tried with the same version of the Black Rooster Plugin Pack I was using (version 2.5.1, downloaded two days ago). Perhaps something on their side that was causing issues? And again, other OpenGL/Vulkan stuff works, right (things like `glxgears` and `vkcube`)?

**Comment by hardyharz3n** [comment]
`glxgears` works, `vkcube` does not – I have no Vulkan, only a lowly P4600 iGPU in an older Xeon.

**Comment by hardyharz3n** [comment]
Tried the 2.5.1. The popup pops up! It was pretty weird seeing how 'my' orginal bundle installed one "Black Rooster Audio.dll" into the designated VST folder which somehow exposed all those .dlls nested in Program Files/BRA/, anyway. BUT not to get too carried away: the darn thing now crashes after entering the serial. Ugh...
