### ISSUE TITLE
yabridge.toml groups not working

### ISSUE THREAD

**Issue by iliaspoulakis** [robbert-vdh/yabridge#37]
Thank you for this great project. It's really easy to set up! I am having issues with the yabridge.toml file. Plugin grouping doesn't work and the ["*"] entry seems to take precedence over all other entries. I narrowed it down to a 3 examples of simple toml files and the associated plugin output (only using FabFilter Pro-Q and Pro-C for this).

**System information**
- Operating system: Manjaro
- Wine version: Wine Staging 5.16
- Installation method: copies, yabridgectl
- yabridge version 1.6.0
- yabridgectl version: 1.6.0

<b>Example 1:</b>

 Here's an example of a simple .toml file that works just fine to showcase that it can be loaded correctly.
<pre>
["*3*"]
editor_double_embed = true
</pre>
Output:
<pre>$reaper  
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] Initializing yabridge version 1.6.0
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] host:         '/usr/bin/yabridge-host.exe'
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] plugin:       '/home/ipoulakis/.vst/windows/FabFilter/FabFilter Pro-Q 3.dll'
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] realtime:     'yes'
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] socket:       '/tmp/yabridge-FabFilter Pro-Q 3-2EKPQbio.sock'
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] wine prefix:  '<default>'
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] wine version: '5.16 (Staging)'
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] 
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] config from:   '/home/ipoulakis/.vst/windows/FabFilter/yabridge.toml'
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] hosting mode:  'individually, 64-bit'
<b>13:54:36 [FabFilter Pro-Q 3-2EKPQbio] other options: 'editor: double embed'</b>
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] 
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] Enabled features:
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] - bitbridge support
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] 
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] [Wine STDOUT] Initializing yabridge host version 1.6.0
13:54:36 [FabFilter Pro-Q 3-2EKPQbio] [Wine STDOUT] Finished initializing '/home/ipoulakis/.vst/windows/FabFilter/FabFilter Pro-Q 3.dll'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] Initializing yabridge version 1.6.0
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] host:         '/usr/bin/yabridge-host.exe'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] plugin:       '/home/ipoulakis/.vst/windows/FabFilter/FabFilter Pro-C 2.dll'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] realtime:     'yes'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] socket:       '/tmp/yabridge-FabFilter Pro-C 2-6CJLMNgl.sock'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] wine prefix:  '<default>'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] wine version: '5.16 (Staging)'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] 
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] config from:   '<defaults>'
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] hosting mode:  'individually, 64-bit'
<b>13:54:36 [FabFilter Pro-C 2-6CJLMNgl] other options: '<none>'</b>
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] 
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] Enabled features:
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] - bitbridge support
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] 
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] [Wine STDOUT] Initializing yabridge host version 1.6.0
13:54:36 [FabFilter Pro-C 2-6CJLMNgl] [Wine STDOUT] Finished initializing '/home/ipoulakis/.vst/windows/FabFilter/FabFilter Pro-C 2.dll'
jack: created client
jack: setting TIME_CRITICAL = 39
jack: activated client
/dev/cpu_dma_latency: set to 0
<b>[1]    197505 segmentation fault (core dumped)  reaper</b>
</pre>

The segmentation fault might be unrelated, but Reaper always crashes the first time it runs (and scans the new plugins) after using `yabridgectl sync`
<pre>
Process 197505 (reaper) of user 1000 dumped core.
                Stack trace of thread 197524:
                #0  0x00007f0bca66f6d7 n/a (libopus.so.0 + 0x506d7)
</pre>

<b>Example 2:</b>

When I now specify a **plugin group** I get the error "WINEPREFIX not found" for any plugins that are matched by the pattern.

<pre>
["*3*"]
group = "eq"

["*2*"]
hack_reaper_update_display = true
</pre>

Output:
<pre>
$reaper          
14:53:54 Error during initialization:
<b>14:53:54 WINEPREFIX not found</b>
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] Initializing yabridge version 1.6.0
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] host:         '/usr/bin/yabridge-host.exe'
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] plugin:       '/home/ipoulakis/.vst/windows/FabFilter/FabFilter Pro-C 2.dll'
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] realtime:     'yes'
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] socket:       '/tmp/yabridge-FabFilter Pro-C 2-DLVWbmoq.sock'
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] wine prefix:  '<default>'
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] wine version: '5.16 (Staging)'
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] 
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] config from:   '/home/ipoulakis/.vst/windows/FabFilter/yabridge.toml'
14:53:54 [FabFilter Pro-C 2-DLVWbmoq] hosting mode:  'individually, 64-bit'
<b>14:53:54 [FabFilter Pro-C 2-DLVWbmoq] other options: 'hack: REAPER 'audioMasterUpdateDisplay' workaround'</b>
</pre>

<b>Example 3:</b>

In this example the options set by the first matched pattern are overwritten when I add the  `["*"]` pattern at the end of the file. I get the same exact output when I put the  `["*"]`  at the beginning of the file (which would be correct).
<pre>
["*3*"]
editor_double_embed = true

["*"]
hack_reaper_update_display = true
</pre>
Output (only relevant lines):
<pre>
14:44:32 [FabFilter Pro-Q 3-1458HILS] plugin:       '/home/ipoulakis/.vst/windows/FabFilter/FabFilter Pro-Q 3.dll'
14:44:32 [FabFilter Pro-Q 3-1458HILS] realtime:     'yes'
14:44:32 [FabFilter Pro-Q 3-1458HILS] socket:       '/tmp/yabridge-FabFilter Pro-Q 3-1458HILS.sock'
14:44:32 [FabFilter Pro-Q 3-1458HILS] wine prefix:  '<default>'
14:44:32 [FabFilter Pro-Q 3-1458HILS] config from:   '/home/ipoulakis/.vst/windows/FabFilter/yabridge.toml'
14:44:32 [FabFilter Pro-Q 3-1458HILS] hosting mode:  'individually, 64-bit'
<b>14:44:32 [FabFilter Pro-Q 3-1458HILS] other options: 'hack: REAPER 'audioMasterUpdateDisplay' workaround'</b>
14:44:32 [FabFilter Pro-C 2-EJKOglqu] plugin:       '/home/ipoulakis/.vst/windows/FabFilter/FabFilter Pro-C 2.dll'
14:44:32 [FabFilter Pro-C 2-EJKOglqu] wine prefix:  '<default>'
14:44:32 [FabFilter Pro-C 2-EJKOglqu] config from:   '/home/ipoulakis/.vst/windows/FabFilter/yabridge.toml'
14:44:32 [FabFilter Pro-C 2-EJKOglqu] hosting mode:  'individually, 64-bit'
<b>14:44:32 [FabFilter Pro-C 2-EJKOglqu] other options: 'hack: REAPER 'audioMasterUpdateDisplay' workaround'</b>
</pre>

I'll sneak a  **feature request** in here:
I think some additional information in `yabridgectl status` would be great, so that you can check if your toml file is being parsed as intended. This would have saved me hours :)
1. The path to the yabridge.toml file that will be used
2. The group that will be assigned to each plugin (next to :: copy). Maybe also the other options.

**Comment by robbert-vdh** [comment]
Thanks a lot for the incredibly detailed report! I've seen that REAPER crash
during plugin scanning before, but it only happens sometimes so I assumed it was
something on REAPER's side (since REAPER's VST2 handling is in places quite
different from other DAWs) and I haven't really investigated if it's something
we can fix on your side. But I'll look into it if I can manage to consistently
reproduce it.

The `WINEPREFIX not found` for group hosts happened because the .so files were
not within a Wine prefix, and that was net getting handled correctly. Funnily
enough the [line after the one throwing this
exception](https://github.com/robbert-vdh/yabridge/blob/1ad9a2b4aba6fa888f3112d8d4d81d37028f0762/src/plugin/host-process.cpp#L153)
is a check to make sure that this exact situation does not cause any issues, but
I clearly haven't tested it :sweat_smile: (rereading the documentation for the
library used there clearly says that this should throw an exception, but I
wrongly assumed it worked the same as the non-constant version which just
creates an entry for the `WINEPREFIX` environment variable when it does not
already exist). This is fixed as of ae402aa805cfa0e5baec13c97be9ccaa82709108.

And that wrong setting being loaded was caused by the TOML parsing library
apparently sorting the tables by their key instead of enumerating them from top
to bottom (it's storing everything in ordered containers, which is why `*` will
always appear first no matter what). Fixing this took a bit more effort than I'd
like to admit since the TOML parsing library definitely was not designed to let
you easily sort things by the order they appear in the file, but I've
implemented this in the latest commit.

Since you're using Manjaro you can just switch to the
[yabridge-git](https://aur.archlinux.org/packages/yabridge-git/) AUR package if
you want to try out these two changes!

And I agree that having a way to check a plugin's configuration in yabridgectl
would be nice to have! There are just two issues here:

- I just don't know what the best way to present the results would be, since
  adding everything to `yabridgectl status` could become super cluttered quite
  quickly.
- The other issue is that yabridgectl has no way to interpret `yabridge.toml`
  files on its own since yabridgectl and yabridge are two completely separate
  code bases. So to do this, we would have to either:

  1. Reimplement the parser directly in yabridgectl. In this case, the bug that
     was causing the issue you were facing wouldn't be reflected in
     yabridgectl's implementation.
  2. Expose a way to essentially output yabridge's initialization message as a
     string in yabridge's library and then use that. This would either require
     linking yabridgectl against yabridge which sounds like a nightmare in
     multiple ways, or to load `libyabridge.so` at runtime (which could work).
  3. Add an entire seperate binary that just outputs the configuration for a .so
     file and call that from within yabridgectl.

  None of these options sound particularly great, so I'm not sure what the best
  course of action here would be.

**Comment by iliaspoulakis** [comment]
Thx robbert, just tested it and it all works perfectly now!

Regarding the reaper crash: For me it crashes consistently when reaper (v6.14) is done scanning the new plugins.  I've noticed though that ocassionally it also crashes before the scan is finished, which might be the crash you've seen as well.

Btw, the yabridgectl-git AUR package fails to build:
<pre>
==> Starting build()...
error: no override and no default toolchain set
==> ERROR: A failure occurred in build().
    Aborting...
</pre>

Regarding the feature request: Thanks for the detailed explanation, I had a hunch this was the case. Would be neat to have that additional info, but if you can't think of a "clean" way to add it then it's probably not a good idea. I'm really impressed with yabridge so far, seems really fast and steady. I will be testing it in the next couple of weeks, I might get back to you with some more feedback :)

**Comment by robbert-vdh** [comment]
Great to hear that it works now! These were some dumb things that I should have caught in my testing but sometimes I get lazy and just assume something works haha. To fix that error you're getting building yabridgectl-git you'll have to set a default Rust toolchain for rustup by running either `rustup default stable` or `rustup default nightly`.

**Comment by robbert-vdh** [comment]
@iliaspoulakis I just wanted to let you know that I finally got around to looking into that crash and it was definitely my mistake! Apparently REAPER is the fastest DAW in the west so the issue only happened there :smile:. The latest commit should no longer crash during the plugin scanning process.

**Comment by iliaspoulakis** [comment]
Works like a charm! Great stuff robbert, thank you :)
