### ISSUE TITLE
bitsery.wrap - wrong path in patch_url

### ISSUE THREAD

**Issue by siborg** [robbert-vdh/yabridge#4]
Hello, just discovered that the path for patch_url variable is wrong in bitsery.wrap. 
it should be . instead of ..

Won't build without correction

Line 8 should be: 

patch_url = file:./subprojects/bitsery-patch.tar.xz

**Comment by robbert-vdh** [comment]
I ran into this as well while I was trying to get the build up and running on an Ubuntu 18.04 image. I'm not sure if this change was intentional or not, but it seems like Meson has changed its working directory from the build directory to the directory the `meson.build` file is located in in Meson 0.54.1. On Meson 0.54.0 and earlier versions you do need the `../`. The whole local patches feature in Meson is pretty lacking to be honest (through it's still nice that it exists).

I will just assume this change was intentional (and that they won't revert it again for Meson 5.55.0) and change the paths here.

**Comment by siborg** [comment]
Thanks Robert and thanks for your efforts to bring the vst plugins to linux. I still cannot get it to work on my arch install (bitwig timing out when scanning the pluggin) but I will presevere.

**Comment by robbert-vdh** [comment]
I've responded to your comment on Reddit! Could you try running the host application directory? So either `yabridge-host.exe`, or `wine yabridge-host.exe.so`. If that doesn't show you a message telling you that you need to pass more command line arguments, then there's probably something wrong. Otherwise you could try running bitwig with the following command line:

```shell
env YABRIDGE_DEBUG_LOG=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2 bitwig-studio-beta
```

If you then try to scan for a plugin, it should write some debug output to `/tmp/yabridge.log` that will probably be helpful for diagnosing the problem.

**Comment by robbert-vdh** [comment]
I changed the paths to be relative to the project root in 8049385e298410cf06ede7f6aa3b31ca65912702. I'm not actually sure how Meson is even resolving these paths, but this was now also the behavior I was getting when I was building the `yabridge-git` package in the AUR.

I'll close this, but let me know if you need any more assistance with compiling.
