### ISSUE TITLE
Yabridgectl sync-update

### ISSUE THREAD

**Issue by iliaspoulakis** [robbert-vdh/yabridge#42]
Hi Robbert,

I've been using yabridge these past couple of weeks and it's truly been fantastic. I've been thinking about
a feature that I'd love to hear your thoughts on.

I'd like to have another sync (update?) command in yabridgectl that only creates new .so files if the existing ones are outdated. I'm thinking of a fast hash comparison (maybe cksum?) against libyabridge before replacing. Not sure if/how this would work with symlinks.

Seems like Reaper is checking the file modification date to determine changes in plugins, the current sync command always triggers a lengthy full rescan of bridged plugins. This new command could be scripted to run before each DAW launch. Then you could simply restart the DAW after installing a new plugin, or when a new yabridge version is released, making the whole experience even smoother :)

**Comment by robbert-vdh** [comment]
I agree that that would be nicer! I went with the current approach (remove the .so file first, then create a new symlink or copy) because you can't overwrite a symlink with a regular file and the other way around also doesn't work, so without removing the existing file first it would not be possible to switch between symlinks and copies (i.e. `cp -f <source_file> <some_symlink>` doesn't work and neither does `ln -s <source_file> <some_regular_file>`). I use Bitwig Studio myself and Bitwig only reindexes plugins when the actual hash changes, but I hadn't considered that other DAWs might not do it that way! (and when I'm testing in other hosts I'm often making changes to yabridge which would need a complete rescan anyway)

I'll make sure to change this for the next release, thanks!

**Comment by iliaspoulakis** [comment]
Awesome, thank you!

**Comment by robbert-vdh** [comment]
I've implemented this in e6af947fe120dedcf6507e83317ef1193a3a7e58! If you want to try it out right now, then you can either download the latest yabridgectl build from the [automated builds](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) page, or if you use Arch or Manjaro then you can simply rebuild the `yabridgectl-git` package.

**Comment by iliaspoulakis** [comment]
Just tried it, works as expected. Thanks a lot!
