### ISSUE TITLE
Bitwig / Opening the wrong plugin window

### ISSUE THREAD

**Issue by abique** [robbert-vdh/yabridge#44]
![image](https://user-images.githubusercontent.com/31200/96750535-57123800-13cc-11eb-9834-ee98fe58ec55.png)

Steps:

- Start Bitwig Studio 3.3 beta 2
- Set the plugin to be hosted inside the engine
- Add Spire
- Add Fabfilter Pro-R
- Close all plugin window
- Open FabFilter plugin window -> the spire one opens.

**Comment by robbert-vdh** [comment]
Hi,

The issue here is the combination of using symlinks and hosting all plugins within a single process. Basically when the first symlink to `libyabridge.so` gets resolved, the dynamic linker will cache the linked .so file. When you then load another symlink to `libyabridge.so` (that belongs to another plugin), ld will see that the .so file is already loaded (since they're symlinks to the exact same file) and it will just reuse the existing library that's already in memory. Yabridge uses `boost::dll::this_line_location()`/`dladr()` to get the path to its `.so` file, but because the second plugin will be loaded from a cached copy of the first `libyabridge.so`, the second plugin will also think it's being loaded from the same path as the first.

The main reasons for using symlinks over copies are the easier setup (no need to change your `PATH` environment variable or move files to `/usr/local/bin`), that they take up slightly less disk space, and that you can't forget to update them when you overwrite your yabridge installation, but because of the above mentioned issue you will have to use either the 'Individually' or 'By Plug-in' hosting modes when doing so. Alternatively it is of course also possible to just use the copy based installation method instead if hosting all plugins within Bitwig's audio engine process is preferred (I personally have not noticed any differences in performance, but given the replies in that KVR thread about Xruns that may not apply to everywhere). In that case you'd have to use `yabridgectl set --method copy=copy`, rerun `yabridgectl sync`, and then make sure that the path containing `yabridge-host.exe` is in your search `PATH` (or else yabridgectl will scream at you).

**Comment by abique** [comment]
Yes I was using symlinks, I now try copies instead.

**Comment by abique** [comment]
Yes it works better that way.

**Comment by robbert-vdh** [comment]
I'll close this issue since this is resolved, but I'll leave the other Bitwig 3.3 related issues open until its out of beta and everything works like it should.
