### ISSUE TITLE
yabridgectl rm only works if directory exists

### ISSUE THREAD

**Issue by iliaspoulakis** [robbert-vdh/yabridge#46]
Maybe yabridgectl rm should also work when the directory has been deleted. This way you clean
up your yabridgectl list.
<pre>
## This works
➜  ~ mkdir test
➜  ~ yabridgectl add ~/test
➜  ~ yabridgectl rm ~/test
## This doesn't work
➜  ~ yabridgectl add ~/test
➜  ~ rmdir test
➜  ~ yabridgectl rm ~/test
Error: No such file or directory (os error 2)
<pre/>

**Comment by robbert-vdh** [comment]
Woops, symlinks were getting resolved for the removed directories, which doesn't make any sense because you already had to specify the absolute path. I'm sure I removed this when adding that functionality to the other directory related functions, but I probably missed it when committing the changes. I fixed this again in c2ec1ce9943f2bf2efd8c705e786c5cb659a2499, thanks!

**Comment by iliaspoulakis** [comment]
Works great, thx Robbert!
