### ISSUE TITLE
Bitwig 3.3 Beta 3 & Loopcloud: unhandled exception

### ISSUE THREAD

**Issue by plaimbock** [robbert-vdh/yabridge#47]
Thanks for giving yabridge a shot! If you're having issues with plugins not working at all or scans timing out then make sure to check out the [troubleshooting common issues](https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues) section of the readme.

**Problem description**
Running Bitwig 3.3 Beta 2 with yabridge 1.7.1: 'Loopcloud Drum.dll' and 'Loopcloud Play.dll' plugins fail to load. The 'Loopcloud.dll' plugin has no issues. I set Biwig plugins to group by manufacterer and had a yabridge.toml file with:

["Loopcloud.so"]
group = "loopcloud"

["Loopcloud Drum.so"]
group = "loopcloud"

["Loopcloud Play.so"]
group = "loopcloud"

**What did you expect to happen?**
They all load so I can use Loopcloud within Bitwig.

**What actually happened?**
Unhandled exception: page fault on read access to 0xffffffffffffffff, invalid program stack in 64-bit code (0x0000000180e9afd1).
Loopcloud Drum.dll and Loopcloud Play.dll fail to load

**System information**
- Operating system: Fedora 32 x86_64
- Wine version: Wine Staging 5.19
- Installation method: symlinks
- yabridge version: 1.7.1
- yabridgectl version: not installed

**Debug log**
Please also include a debug log if possible. If you are reporting an issue with yabridgectl, then you can omit this section.

1. First make sure that there are no leftover Wine processes left running in the
   background using `wineserver -k`.
2. Launch your host from a terminal using
   `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2 <host>`,
   e.g. `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2 bitwig-studio`.
3. Try to scan or load the plugin that's causing issues.
4. `/tmp/yabridge.log` should now contain a debug log. You can either attach
   this log directly to the issue by dragging the file onto this text box, or
   you could upload the contents to a website like GitHub's Gists or Hastebin.
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5429980/yabridge.log)
[backtrace.txt](https://github.com/robbert-vdh/yabridge/files/5429981/backtrace.txt)

**Comment by robbert-vdh** [comment]
Does this also happen with Bitwig 3.2, or 3.3 beta 1 when using one of [these builds](https://github.com/robbert-vdh/yabridge/actions?query=branch%3Aremoveme%2Fbitwig-3.3-beta-hack)? In beta 2 the audio engine will crash when you remove a plugin, no matter the plugin or the plugin format. They've already fixed this for the next beta, but for now beta 2 is probably best avoided if you use plugins.

**Comment by plaimbock** [comment]
Thank you for your quick reply. I tried Bitwig 3.2.8 with yabridge from https://github.com/robbert-vdh/yabridge/suites/1388301414/artifacts/22917325 and got the same results. I'll wait for the next Bitwig 3.3 beta and then try again.

**Comment by robbert-vdh** [comment]
I just looked at the actual log files (I didn't have the time yesterday, sorry!) and the issue is indeed unrelated to the plugin hosting issues with Bitwig 3.3 beta 2 (that issue only comes in when the plugin gets removed from the audio engine process). The LoopCloud plugin here is segfaulting during shutdown. I can't download their plugins without giving them my credit card details so I couldn't check it out for myself. If you haven't already done so then installing `vcrun2019` through winetricks might help, but otherwise it's likely just a Wine bug or LoopCloud that's doing something. Yabridge will ignore crashes when they happen during shutdown because of situations like this so if you just close Wine's crash dialog then everything else should be fine, but for this approach to work you will need to disable the plugin group because otherwise a single LoopCloud plugin instance crashing during shutdown will take down the entire group with it.

**Comment by plaimbock** [comment]
Thanks for the tip. Tried 3.3 Beta 2, plugins hosted individually, with regular 1.7.1, no yabridge.toml, and vcrun2019 but the Loopcloud Play & Drum plugins still fail. I'll wait for Wine+Staging 5.20 plus the next BWS Beta and then try again.

**Comment by robbert-vdh** [comment]
Sorry that it took so long! I installed version 5.2.20 of the Loopcloud software and plugins in a clean prefix using wine-tkg 5.20 and the latest commit of yabridge (fa01ac843ba4b3a04a912c4ef3d9454fb72944bb as of writing). I've also tested with plain Wine Staging 5.20. The Loopcloud software opens just fine and the auto update also works out of the box without any overrides, but I don't have an account so that probably doesn't mean much. The plugin that's just named Loopcloud seems to work just fine although it doesn't do much because I'm not logged in. The 'Loopcloud Play' and 'Loopcloud Drum' plugins tell me that the Loopcloud installation is corrupted with a JS_EXEC_FAILED error code and then segfault after that at the moment the plugin would start getting ready to process audio, but since I've never logged in to Loopcloud may be actually be missing a ton of files. Other than that error (and the expected segfault that follows it) the software seems to work fine in a clean Wine Staging 5.20 prefix.

**Comment by robbert-vdh** [comment]
So apparently if you cancel partway through the registration process you still get an account just with no active trial, guess I was wrong about that. When logged in both the regular software and the plain 'Loopcloud' plugin work just fine. I can select a sample in the Loopcloud software and then play them through the plugin. Those 'Loopcloud Play' and 'Loopcloud Drum' however still give the same corrupt installation/JS_EXEC_FAILED errors. I tried running with `WINEDEBUG=warn+all` to see if that gave something useful, but there's nothing out of the ordinary there. The error description and the fact that there are a bunch of encoded JavaScript files in `drive_c/users/<user>/Application Data/Loopmasters` gives me the suspicion that either the installer was supposed to install some kind of Node.js runtime but didn't, or that it's failing to decode those files, but I haven't dug deep enough into this to tell what's going on. Anyways, this is either this particular version of those plugins just being broken (seems unlikely, but it could happen), or Wine that's doing something strange.

**Comment by plaimbock** [comment]
Thank you for your elaborate feedback. I've also seen the JS_EXEC_FAILED errors. Also saw them during installation of a UJAM plugin. Re not needing overrides: confirmed. I just tried again with a clean 5.20 prefix and upgrading indeed worked fine. Now Loopcloud says I did too many installations so have to wait until they reset my account. Since the issue seems not related to yabridge I'm closing this. Thank you for all your help!

**Comment by robbert-vdh** [comment]
Yeah I've also seen this before somewhere else. These plugins are probably all made by the same manufacturer. They're bundling Node.js in those plugin .dll files (that's also why they're so huge), but I'm not sure whether the issue is that it's unable to run those NOde.js binaries or that the decoding of those files over at `ProgramData/Loopmasters/Loopcloud*` is failing (Wine's not outputting any relevant warnings or fixme here). This sounds like something that should be reported on Wine's bug tracker if it's not already there!

**Comment by robbert-vdh** [comment]
As of commit 95badeb1bc319dd9b855af68651349cfbc76cee3 you can enable the `disable_pipes` option for these (and presumably other ujam/Gorilla Engine plugins) to 'fix' this `JS_EXEC_FAILED` error!
