### ISSUE TITLE
Scaler 2.1.2 UI updates are very slow

### ISSUE THREAD

**Issue by klingtnet** [robbert-vdh/yabridge#49]
**Problem description**
The UI of [Scaler 2.1.2](https://www.scalerplugin.com/) is almost unresponsive no matter if the input is a mouse click or an incoming MIDI event, audio works fine though.  This does not happen for Scaler 1.8.1 which works fine with yabridge.

**System information**
- Operating system: `Linux kn-portable-arch 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux`
- Wine version: `wine 5.20.1`
- Installation method: `copies, yabridgectl`
- yabridge version: `1.7.1`
- yabridgectl version: `1.7.1`

**Debug log**
Please also include a debug log if possible. If you are reporting an issue with yabridgectl, then you can omit this section.

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5452218/yabridge.log)

PS: Thanks for developing `yabridge` :ok_hand:

**Comment by robbert-vdh** [comment]
Are you using an iGPU? I've heard more reports of Scaler 2 being slow on integrated graphics. They're using OpenGL so luckily it's not an issue with WineD3D, but if you're using a laptop with a dGPU then switching to that should help. On my desktop with an NVIDIA GPU the GUI updates smoothly (albeit with a slight 100~200 ms delay, but that's Scaler doing something weird).

**Comment by klingtnet** [comment]
Thanks for the quick reply, but it is not an iGPU but a Radeon RX 550 in my desktop machine.

**Comment by robbert-vdh** [comment]
Wine runs under Wayland with XWayland, so maybe Scaler 2's OpenGL context is not getting initialized correctly? I'm actually kind of surprised that yabridge even works under Wayland since I have to call into X11 directly to do the window management :grin:. Could you check if it's also slow under X11? It may also just be a Mesa thing since those iGPUs should have more than powerful enough to handle Scaler 2's GUI, and there don't seem to be any issues when using NVIDIA GPUs.

**Comment by klingtnet** [comment]
Sorry, I was not able to start a X11 session, it always failed directly after the login :man_shrugging:

**Comment by cameronleger** [comment]
It's worth noting that I'm running slightly similar versions but I _do not_ see this sluggish behavior, in fact there's really no complaints at all about the UI or MIDI interactions, which is impressive to me mainly because on a 4K screen with large plugin windows, a handful of VSTs have sluggish issues with this.

* Operating system: Linux zeus 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
* Wine version: wine-staging 5.6.1.r0.g4c160ec8+wine.5.6.r0.g4cdb7ec829-1
* Installation method: copy next to DLL, symlinked to a common place
* yabridge version: 1.5.0.r5.g504102e-1
* Scaler version: 2.0.2
* Compositor: picom 1384_Next.103.gc212f65_2020.08.14-1
* WM: personal fork i3-gaps-next-git 4.16.1.r107.g41264e54-3

**Comment by klingtnet** [comment]
@cameronleger This supports the assumption that the issue is related to Wayland since `picom` is an X11 compositor, right?

**Comment by robbert-vdh** [comment]
@cameronleger What GPU are you using if I may ask? I'm pretty sure that other person who was having performance issues with Scaler 2 and solved it by switching to his NVIDIA dGPU was on Xorg (since PRIME doesn't work on Wayland), but I'm curious to see if there's a pattern here. I know one other person with an Intel iGPU that was having performance issues with Scaler 2, but I'm not sure whether he was on Xorg or Wayland.

**Comment by cameronleger** [comment]
Almost always it's a GTX 1070 from NVIDIA; I have a GTX 1080 Ti that's always idle/off in a Bumblebee-like situation and for pass-thru but I'm thinking I should make that the daily driver since I basically never use the VM anymore.

I keep way more windows open that I should (20+ workspaces) so I frequently am close to the limit of GPU RAM and can get some compositing-related artifacts in the worst cases. Then, I either stop or restart picom, and honestly I haven't tried it with Scaler 2 but very few plugins change their behavior with it on vs. off.

**Comment by robbert-vdh** [comment]
Hmm that would support my theory of it being some compatibility issue with Mesa's OpenGL implementation and Scaler 2 (or Wine, but that seems less likely). Right now all reports I've heard of Scaler 2 being sluggish have come from people using either Mesa with Intel or Mesa with AMD, and everything seems to work fine for people using NVIDIA's propietary drivers.

**Comment by klingtnet** [comment]
Is there a proprietary AMD driver anymore?  I thought _amdgpu pro_ is just some user space frontend.

**Comment by plaimbock** [comment]
> Is there a proprietary AMD driver anymore? I thought _amdgpu pro_ is just some user space frontend.

https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-20

**Comment by robbert-vdh** [comment]
Yeah from what I've read [AMDGPU PRO](https://wiki.archlinux.org/index.php/AMDGPU#AMDGPU_PRO) (the propietary alternative to Mesa's OpenGL driver) is usually worse in terms of raw performance compared to Mesa, but some 'professional' software won't run without these drivers. It would be interesting to see if Scaler 2's performance issues go away with those drivers, since that would mean that there's something wrong with Mesa that's causing these issues (or Scaler 2 is doing something weird and the drivers are making up for it, but since I don't think these issues are present on Windows that's probably not the case here).

**Comment by klingtnet** [comment]
Unfortunately, it does not show any GUI when using `amdgpu-pro`.

**Comment by robbert-vdh** [comment]
@klingtnet Does `glxgears -info` work with AMDGPU PRO? You'd think Scaler 2 wouldn't be doing things that would break two entire driver stacks in different ways.

**Comment by klingtnet** [comment]
```sh
GL_RENDERER   = Radeon RX 560 Series
GL_VERSION    = 4.6.14756 Compatibility Profile Context
GL_VENDOR     = ATI Technologies Inc.
GL_EXTENSIONS = GL_AMDX_debug_output GL_AMD_blend_minmax_factor GL_AMD_conservative_depth GL_AMD_debug_output GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_sample_positions GL_AMD_gcn_shader GL_AMD_gpu_shader_half_float GL_AMD_gpu_shader_int16 GL_AMD_gpu_shader_int64 GL_AMD_interleaved_elements GL_AMD_multi_draw_indirect GL_AMD_name_gen_delete GL_AMD_occlusion_query_event GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_sample_positions GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_atomic_counter_ops GL_AMD_shader_stencil_export GL_AMD_shader_stencil_value_export GL_AMD_shader_trace GL_AMD_shader_trinary_minmax GL_AMD_stencil_operation_extended GL_AMD_texture_cube_map_array GL_AMD_texture_texture4 GL_AMD_transform_feedback3_lines_triangles GL_AMD_transform_feedback4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_snorm GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_envmap_bumpmap GL_ATI_fragment_shader GL_ATI_meminfo GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_buffer GL_EXT_copy_texture GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_histogram GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_separate_specular_color GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texgen_reflection GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_bptc GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_explicit_multisample GL_NV_float_buffer GL_NV_half_float GL_NV_primitive_restart GL_NV_shader_atomic_int64 GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_vdpau_interop GL_OES_EGL_image GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays GL_WIN_swap_hint
VisualID 940, 0x3ac
```

**Comment by robbert-vdh** [comment]
So at least AMDGPU PRO works, so it's not that. I'm really curious now what Scaler 2's doing that's breaking two sets of drivers. I haven't had the time to set up Scaler 2 on my laptop yet, but I'm curious of any of the [Mesa](https://docs.mesa3d.org/envvars.html) debugging options could shed some light on the situation. Especially `LIBGL_DEBUG`, `LIBGL_SHOW_FPS`/`GALLIUM_HUD` (to verify that it's running at 60 fps, I can't get mangohud to work with Scaler 2 but from checking out a 144 fps recording I can conclude that it's locked to 60 here), and the OpenGL overrides sound promising to at least get some sense of what's going on here.

**Comment by plaimbock** [comment]
Normally I use Wayland where Scaler2 runs very slow but I just switched to an Xorg session and Scaler2 then seems to run fine (Fedora 33 + updates, Wine 5.20, yabridge 1.7.1). So it may have something to do with Wayland. What's next? Suggestions welcome.

**Comment by plaimbock** [comment]
Here is glxgears -info on Xorg and glxgears -info on Wayland
[glxgears_info_Xorg.txt](https://github.com/robbert-vdh/yabridge/files/5477813/glxgears_info_Xorg.txt)
[glxgears_info_Wayland.txt](https://github.com/robbert-vdh/yabridge/files/5477814/glxgears_info_Wayland.txt)

**Comment by robbert-vdh** [comment]
Oh, by the way, apparently there is a way to use software rendering instead of OpenGL: https://forum.scalerplugin.com/t/scaler-2-black-empty-window/3540/8

I looked for something like that before and I couldn't find a setting for it, but apparently there's a hidden option you can add to a config file. Have you tried that? While performance wise the plugins runs fine on my system, it's still a bit glitchy with black screens from time to time (also seems to happen on Windows from what I can gather from that thread) and interacting with the UI has a slight delay. With software rendering all those issues disappear and the plugin seems much snappier. I'll add this to the readme since I'm sure more people use the plugin.

**Comment by plaimbock** [comment]
Thanks for the tip @robbert-vdh  I switched back to a Wayland session and added that key in Scaler2.settings. Now it also runs fine in Wayland :-)

**Comment by klingtnet** [comment]
> Oh, by the way, apparently there is a way to use software rendering instead of OpenGL: https://forum.scalerplugin.com/t/scaler-2-black-empty-window/3540/8
> 
> I looked for something like that before and I couldn't find a setting for it, but apparently there's a hidden option you can add to a config file. Have you tried that? While performance wise the plugins runs fine on my system, it's still a bit glitchy with black screens from time to time (also seems to happen on Windows from what I can gather from that thread) and interacting with the UI has a slight delay. With software rendering all those issues disappear and the plugin seems much snappier. I'll add this to the readme since I'm sure more people use the plugin.

This works like a charm, thank you very much!

**Comment by robbert-vdh** [comment]
Great to hear! I think there might just be something wrong with their OpenGL implementation. Even when running the plugin completely standalone (it doesn't seem to be a fan of yabridge's embedding method when using OpenGL rendering) it still does some weird things. For instance it highlights the previous key when hovering over a new one. Disabling software acceleration seems to fix all rendering issues with the plugin. I've added this to the readme, so hopefully other people who run into this in the future won't have to go through these same struggles :grin:.
