### ISSUE TITLE
PSP VintageWarmer Gui crash when loding plugin or song in Renoise

### ISSUE THREAD

**Issue by martinbangens** [robbert-vdh/yabridge#50]
**Problem description**
[PSP VintageWarmer](http://www.pspaudioware.com/plugins/dynamic_processors/psp_vintagewarmer2/) Gui crash when loading plugin or song in Renoise. I'm not sure if it a configuration problem with wine. its PSP VintageWarmer (LE) plugin.

**What did you expect to happen?**
The plugin to load normally 

**What actually happened?**
The plugin throw error at start and seem to preform slow or give a lot of xruns at a 1024
 buffer size.

**System information**
I use Manjaro and compiled this [wine version ](https://github.com/nine7nine/pkgbuilds_nspa/tree/master/wine-nspa). and yabridge from AUR + yabridgectl AUR. and 5.9.1-1-rt19-MANJARO kernel

`env YABRIDGE_DEBUG_FILE=/home/marbangens/yabridge.log YABRIDGE_DEBUG_LEVEL=2 WINEFSYNC_SPINCOUNT=128 WINEFSYNC=1 WINE_RT_POLICY=RR WINE_RT_PRIO=82 VST_PATH=/home/marbangens/.vst:/usr/lib/vst:/usr/local/lib/vst:/home/marbangens/.wine/drive_c/Program\ Files\ \(x86\)/ /usr/local/bin/renoise-3.2.2`

**Comment by martinbangens** [comment]
Oh It seem that The Korg ms-20 plugin makes the xruns, PSP VintageWarmer crash when loading it into the song but seems to be working after.
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5541233/yabridge.log)

**Comment by robbert-vdh** [comment]
This happened for all plugins loaded as effects into Renoise. Apparently there was an off-by-one error in the way yabridge loads speaker arrangements, and since Renoise is the only DAW that uses those this issue never popped up before (and for instruments Renosie for whatever reason reports that it's thousands upon thousands of speakers instead of only two, so missing one was never an issue there). I've fixed this in ed5f0c42d98b2d6d6fba701b670a2ec1864cb1a5! You can update to this commit by installing `yabridge-git` from the AUR and then rerunning `yabridgectl sync` after updating.

**Comment by martinbangens** [comment]
Cool, I don't know what you did but for me It helped Enable Run all plugins as sandboxes. I got you're update from aur. And I'm happy. Disto::Fx My favorite distortion plugin seem to work really nice, love this project.
