### ISSUE TITLE
Ardour doesn't recognize bridged VST plugins

### ISSUE THREAD

**Issue by P-Mousavi** [robbert-vdh/yabridge#56]
As you mentioned in the README section,**Ardour6.3** should work,but I'm unable to load any of my Windows VST plugins in the ardour6 plugin browser.
I've followed the instructions and set everything up perfectly and the result is that both Carla and Bitwig-studio can see the plugin(Kontakt6) and import it,but ardour cannot.BTW the file **Kontakt.dll** and "Kontakt.so" reside in `~/.vst` and that location has been added to the ardour's VST search path,and ardour has re-scanned the VSTs after that.
Currently I'm using the **symlink** method,but the **copy** method also doesn't work for ardour.

I wanted to know is there any additional steps I should take to make that work in ardour? There was no additional information about ardour both in the issues and in the usage instructions.

Thanks.Regards.

**Comment by robbert-vdh** [comment]
Hi,

First of all just to make sure, for Ardour you really have to use the copy installation method. Otherwise you won't be able to open multiple different plugins. yabridgectl should be able to guide you through setting those copies up correctly (just make sure to log out after you change your search `PATH` and yabridgectl no longer shows any warnings).

You say that Ardour cannot import the plugin, how far have you gotten? Can you select the plugin in the plugin list or does it not show up there?

**Comment by P-Mousavi** [comment]
Hi robbert.Thanks for the fast reply.
Again I changed the method to **copy** and opened ardour.No luck.
And the plugin doesn't show up in the plugin list at all.My last solution was to copy all the **.dll**s beside their **.so** counterparts to **/usr/lib/lxvst** to see if it helps,then they suddenly showed up in the Ardour's "Searching for plugins" popup window(only once),but still not in the plugin list.

**Comment by robbert-vdh** [comment]
I'd advise leaving those dll files in the Wine prefix to make sure things don't end up breaking in the future, but that's not the issue here so let's ignore that for now :grin:.

Could you check for me:

- When run you `env -i HOME="$HOME" $SHELL -l -c 'which yabridge-host.exe'` from a terminal, does that print the path to `yabridge-host.exe`? (yabridgectl also checks this for you when you run `yabridgectl sync`)
- If that does print the correct path to `yabridge-host.exe` (and you've logged out after changing any environment variables), then running `yabridge-host.exe` form a terminal (just that, no `wine` in front of it or anything) prints a bunch of Wine stuff followed by `Usage: yabridge-host.exe <vst_plugin_dll> <endpoint_base_directory>`, right? (it should, since it was working in Carla and Bitwig)
- If all of that worked as expected, then could you try running Ardour from the terminal with:

  ```shell
  env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1 ardour6
  ```

  And then go to Ardour's settings and clear the VST cache and blacklist. If you then go to 'Edit VST path' and close the dialog again, it will ask you to rescan for plugins. After that's done (and the plugins still don't show up), could you upload `/tmp/yabridge.log` here? (by dragging and dropping the file onto the text field)

**Comment by P-Mousavi** [comment]
Oh  that got fixed automatically after logout ! 😅
I thought the logout part was unnecessary cuz the `export PATH=...` statement was in my `~/.zshenv` file not `~/.zprofile` and **yabridgectl** didn't show any warnings.
But the actual solution was to restart the **wineserver** or so?

However thanks for creating such an amazing piece of software.Hope these kind of compatibility layers further increase the linux adoption to catch the attention of some musical technology manufacturers to consider linux desktop more :)

**Comment by robbert-vdh** [comment]
Great to hear it's working now! The log out part is needed because applications launched from the GUI indirectly inherit their environment from the login shell, and the login shell of course only reads `~/.zprofile` and `~/.zshenv` at the moment you log in (the latter doesn't work on Arch/Manjaro for this purpose). So if you want to change environment variables for those applications, then you will have to log out.

**Comment by P-Mousavi** [comment]
Sorry I encountered a strange problem unfortunately.
Everything worked fine in ardour until I closed and reopened the session.Now ardour just exits when I select my session in the **Session setup** window and also logs nothing in terminal.**YABRIDGE_DEBUG_FILE** env variable doesn't help either.I can re-open the previous projects,but only the one contains an instance of yabridge :( doesn't work
What can be the cause of that?

**Comment by robbert-vdh** [comment]
When you set `YABRIDGE_DEBUG_FILE` to `/tmp/yabridge.log` the output gets written to that file instead of the terminal, so you should check the contents of that file instead or you should not set the environment variable to have stuff printed to your terminal. LIke I said, `~/.zshenv` is broken in Arch and probably also in other distros, so have you tried modifying your `PATH` in `~/.zprofile` instead?

**Comment by P-Mousavi** [comment]
There was nothing logged to **/tmp/yabridge.log** nor to the terminal.This time the problem is not that the ardour doesn't recognize the VSTs,but looks like Ardour wants to forget them.When I save the session the plugin gets kind of deleted(the **plugins** folder).I'm not sure that's a bug in ardour or not.

**Comment by robbert-vdh** [comment]
Does Ardour print anything when it crashes? Does it crash with a `SIGSEGV` or a `SIGABRT`? I'm far from an expert on Ardour, but I have not seen this behavior before.

**Comment by P-Mousavi** [comment]
No.It returns with exit status of zero.Can firejail be a problem here? I've been using it for a while now and there was no problem with ardour either.Have you tested yabridge in a similar situation? BTW I use Manjaro 20.2.

**Comment by robbert-vdh** [comment]
I just checked for you what happens for me when I load an Ardour project after modifying my `PATH` to no longer contain yabridge's files, and that gets me a nice error popup and no segfaults, so `PATH` being incorrect is probably not the issue here: 
![afbeelding](https://user-images.githubusercontent.com/748520/99737408-851c9200-2ac8-11eb-8451-52c2dabdc8fa.png)

I would try without firejail.

**Comment by P-Mousavi** [comment]
That happens even without using firejail.New sessions with plugins other than yabridge(e.g Zyn) saves well and I'm able to re-open them without any problem.What's your ardour version?(mine is 6.3.0)

**Comment by robbert-vdh** [comment]
This is Ardour 6.3-3, but Ardour's been working this way for a long time. And also, since you're on Manjaro, you could have just used the [yabridge](https://aur.archlinux.org/packages/yabridge) and [yabridgectl-git](https://aur.archlinux.org/packages/yabridgectl-git) AUR packages instead of manually downloading the binaries from GitHub. That would have saved you from having to modify environment variables.

If you start Ardour without firejail then `YABRIDGE_DEBUG_FILE` should work again since that doesn't work with firejail. If you start ardour like this **without firejail**:

```shell
env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1 ardour6
```

And that doesn't create a `/tmp/yabridge.log` file, then there's something wrong with your Ardour installation.

**Comment by P-Mousavi** [comment]
I have to mention that the bridged plugins can be successfully loaded if be set up on top of Carla(in ardour).But the desire is to eliminate the middleware since carla has a [bug](https://github.com/falkTX/Carla/issues/1053) that cannot load the Kontakt instruments and because of that I decided to give yabridge a try.

And here's the yabridge log after adding an instance of it to one my projects:
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5570422/yabridge.log)

**Comment by robbert-vdh** [comment]
There are no errors in that log. So everything works as it should now?

**Comment by P-Mousavi** [comment]
Oh yeah,yabridge hasn't that Kontakt problem but still I need Carla to run it flawlessly in Ardour for now.The disadvantages of this method are:
1) A bit more latency
2) I only see "Carla-Patchbay" as the plugin name,not the real name of the VST plugin
3) Carla has less flexibility when it comes to I/O ports(with yabridge I can change them dynamically but with carla there are presets: 8,16,32,64 audio input/output)

However I appreciate your help and thank you for your patience 🙂.

**Comment by robbert-vdh** [comment]
Sorry but I still don't really get what the current situation is. Why do you need Carla? Why can't you use Kontakt through yabridge in Ardour? Now that you're no longer using firejail, does loading projects work again without Ardour mysteriously closing?

**Comment by P-Mousavi** [comment]
No.Here's the point.With yabridge loaded directly,ardour mysteriously closes.But with YABridge on top of Carla,everything works fine.So why am I still using yabridge and don't stick with just Carla? Cuz Carla cannot load the saved Kontakt instruments correctly,but yabridge can.So Kontakt on yabridge on carla on ardour :D

If you could set it up correctly then indeed something is wrong with my setup in my system.Whatever it is it now works almost as I expected,and latency is not my biggest concern.I want stability and reliability, and with the help of wine,carla and yabridge everything works fine and I can do my hobby music production entirely in linux.That's enough for now.Maybe I should try to file a bug report to the Ardour team for that.
We can close this thread for now.

**Comment by P-Mousavi** [comment]
I think I found something useful.I saw this in the ardour logs(not from terminal,but from the little button in the top-right corner with a flashing red light):
```
2020-11-21T15:58:43 [ERROR]: XML error: invalid character in attribute value in /tmp/ramdisk/demo2/demo2.ardour at line 1044:48
2020-11-21T15:58:43 [ERROR]: XML error: attributes construct error in /tmp/ramdisk/demo2/demo2.ardour at line 1044:48
2020-11-21T15:58:43 [ERROR]: XML error: Couldn't find end of Start Tag Controllable line 1044 in /tmp/ramdisk/demo2/demo2.ardour at line 1044:48
2020-11-21T15:58:43 [ERROR]: XML error: PCDATA invalid Char value 28 in /tmp/ramdisk/demo2/demo2.ardour at line 1044:48
```
and the line 1044 is this:
```
<Controllable name="Dyn KS - Violin Eû" id="766" flags="" value="0" parameter="268"/>
```
and the column 48 is the character **û**.All of the trouble I faced was because of this 😂.
And where did that character came from?
My Kontakt default multi !

So the problem wasn't yabridge nor firejail.
I replaced the default multi of kontakt with an empty one and now it works beautifully !
Again thanks this great work :)

**Comment by robbert-vdh** [comment]
Wow that's a real head scratcher and a half. Were those characters that show up on GitHub as � invalid UTF-8? I don't even know if VST2 allows UTF-8, but probably not (since all lengths for names and things are capped at very short lengths).

**Comment by P-Mousavi** [comment]
No.Those were [0x001C](https://www.compart.com/en/unicode/U+001C) and [U+0097](https://www.compart.com/en/unicode/U+0097) respectively.Certainly valid.

I don't know where those name came from.It even might be the result of corruption.Whatever it was it's now solved!

**Comment by robbert-vdh** [comment]
It may still be a good idea to report this to the Ardour folks (if it is not already fixed in the master branch) since this shouldn't cause any crashes, but I'm glad that at least you've at least figure out what was causing these weird issues!
