### ISSUE TITLE
Add note about `.config/yabridgectl/config.toml` for manual configuration

### ISSUE THREAD

**Issue by GavinRay97** [robbert-vdh/yabridge#68]
I was going to add a PR for this but found when looking in the source code the functionality already exists.
```toml
# ~/.config/yabridgectl/config.toml

method = 'copy'
plugin_dirs = [
    '/home/user/.wine/drive_c/Program Files/Common Files',
    '/home/user/.wine/drive_c/Program Files/Steinberg/VSTPlugins',
    '/home/user/.wine/drive_c/Program Files/VSTPlugins',
    '/home/user/.wine/drive_c/Program Files (x86)/Steinberg/VSTPlugins',
    '/home/user/.wine/drive_c/Program Files (x86)/VstPlugins',
    '/home/user/.wine-spire/drive_c/Program Files/Steinberg/VSTPlugins',
]

[last_known_config]
wine_version = 'wine-6.0-rc1'
yabridge_host_hash = -6418133867175857968
```

Might be useful info for others, to add to README. Unsure if it was left out for a reason though (IE manually altering `plugin_dirs` breaks things).

**Comment by robbert-vdh** [comment]
I didn't mention it because it shouldn't be necessary to edit it by hand (except maybe for reverting back to automatic path detection after manually setting a path, there's currently no option for that). But of course, you can! Just beware that the TOML serialization library used doesn't retain any comments or manual formatting, so those things would be lost after the file gets updated again. The contents of the config file can be found in [config.rs](https://github.com/robbert-vdh/yabridge/blob/a54814e6109240542c514a62ce92c7a46cc6d720/tools/yabridgectl/src/config.rs#L48).

**Comment by GavinRay97** [comment]
Ahh understood, that makes sense :+1: 

I'm a bit clumsy so often find it easier to edit config files in `nano` or `micro` versus typing or copy/pasting in terminal, which was the only reason I went looking haha

**Comment by robbert-vdh** [comment]
Resetting the path detection back to automatic path detection is now possible as of yabridge 3.0.0 with `yabridgectl set --path-auto. There's also the option to permanently disable post-installation setup checks with `yabridgectl set --no-very true`. With that there should be no reason to manually edit yabridgectl's configuration file anymore. Feel free to open a new issue if you run into any other issues!
