### ISSUE TITLE
Build of 2.2.1 fails on Fedora 33

### ISSUE THREAD

**Issue by plaimbock** [robbert-vdh/yabridge#72]
**Problem description**
The build of 2.2.1 fails on Fedora 33

**What did you expect to happen?**
Build does not fail :)

**What actually happened?**
FAILED: yabridge-host-32 
wineg++  -o yabridge-host-32 yabridge-host-32.p/src_common_configuration.cpp.o yabridge-host-32.p/src_common_logging.cpp.o yabridge-host-32.p/src_common_serialization.cpp.o yabridge-host-32.p/src_common_communication.cpp.o yabridge-host-32.p/src_common_utils.cpp.o yabridge-host-32.p/src_wine-host_bridges_vst2.cpp.o yabridge-host-32.p/src_wine-host_editor.cpp.o yabridge-host-32.p/src_wine-host_utils.cpp.o yabridge-host-32.p/src_wine-host_individual-host.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -m32 -Wl,--start-group /usr/lib/libboost_filesystem.so -lpthread -lxcb -Wl,--end-group
/usr/bin/ld: relocatable linking with relocations from format elf64-x86-64 (/usr/lib64/wine/libwinecrt0.a(exe_entry.o)) to format elf32-i386 (yabridge-host-32.Rb5PbA.o) is not supported
winebuild: /usr/bin/ld failed with status 1
winegcc: /usr/bin/winebuild failed
ninja: build stopped: subcommand failed.

**System information**
- Operating system: Fedora 33
- Wine version: Wine-Staging 6.0rc2
- Installation method: n/a
- yabridge version: 2.2.1
- yabridgectl version: n/a
-

**Comment by robbert-vdh** [comment]
That specific linking issue got fixed shortly after Wine 6.0 rc2. You should update to rc3 or downgrade to Wine Staging 5.22 to build yabridge. Also, yabridge 2.2.1 won't build correctly with Wine 6.x because of some changes made in Wine 5.7 that they silently reverted reverted. If you're building from source with Wine 6.0 then you'll have to build from the master branch instead (or from [this commit](https://github.com/robbert-vdh/yabridge/commit/449b17b5e2297e52e3a3adf3eeff18c2b9d51194).

**Comment by plaimbock** [comment]
Thanks for the quick feedback! I'll wait for rc3 in the F33 testing repo and then build from master.
