### ISSUE TITLE
Why wine-staging?

### ISSUE THREAD

**Issue by taji** [robbert-vdh/yabridge#73]
I've read your docs and the wine docs but I'm still a bit confused (sorry, but a bit ignorant re: WINE so please take these questions as genuine:

- Is it considered a good practice to install wine-staging rather than wine-stable (not just for ya-bridge but in general)?
- Currently, does it matter if I install wine-staging-5 or wine-staging-6?  The 6 version seems to be the default when installing staging. 
- Is there something intrinsic to the wine-staging binaries that yabridge depends on? So installing wine-stable will never work with ya-bridge?
    - If so, are there plans to implement a wine-stable compatible version of ya-bridge in the future?

Thanks :)

**Comment by robbert-vdh** [comment]
Hi!

Wine Staging is regular Wine with a bunch of additional patches on top. These patches often include quite substantial changes to improve performance or compatibility, and Wine Staging sort of acts as a...staging area for these new patches to grow and mature a little before they get merged into Wine proper (although some patches have been living in Wine Staging for many years now). Because of this Wine Staging tends to offer both better compatibility and performance (especially with things like esync and fsync, although the latter is not part of Wine Staging). In theory there could also be changes in there that could cause bugs or break things, but I've never ran into a situation where something that didn't work with Wine Staging did work with regular Wine. That's why Wine Staging or a derivative of it is the default choice for things like gaming, and also why I'd advise using Wine Staging or a fork of it as a default. And thus to answer your third question: no, there's no reason why yabridge wouldn't work with non-staging versions of Wine. It just tends to be a good idea in general to use Wine Staging over plain Wine.

As for which version of Wine to use, I'd always just use the latest version unless you run into specific issues with that version. The builds on GitHub are also built with relatively recent versions of Wine (I think the CI just got upgraded to Wine Staging 5.22), and since Winelib applications like yabridge are not perfectly backwards compatible those builds won't work with Wine versions below at least 5.4-ish.

**Comment by taji** [comment]
Thanks for the quick and thorough response.  Makes sense.  Will install recommended version as per here: 

https://wine.htmlvalidator.com/install-wine-on-ubuntu-20.04.html

Closing the issue. :)

**Comment by taji** [comment]
Questions answered, so closing.
