### ISSUE TITLE
No sound in EZdrummer 

### ISSUE THREAD

**Issue by magillos** [robbert-vdh/yabridge#75]
**Problem description**
Hi, we actually met on reddit before where you gave me a great support with Ezdrummer Plugin. It launches now but I can't make it produce any sound.

**What did you expect to happen?**
I load the plugin in Ardour and I am able to open it up and go through all the features. When I play a track within the plugin it seems to be playing it but I can't hear or record any sound in Ardour. The Ardour's midi meter seems to be active but not the audio one of the track. I checked MT-drumkit as well and it works perfect; I also compared all the jack connections between these two plugins to make sure I didn't miss anything. EZdrummer works mostly fine with some old instance of linvst bridge too. 
The log included is from clean Ardour session with just one EZdrummer track. Apologies, it's massive.
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5770307/yabridge.log)

**System information**
- Operating system: Arch
- Wine version: Wine Staging 5.22
- Installation method: yabridgectl
- yabridge version: 2.2.1.r518.g37c4397 (git AUR version)
- yabridgectl version: 2.2.1.r520.gc554b9b (git AUR version
- EZdrummer verson: 2.1.8

**Comment by robbert-vdh** [comment]
Sorry it took so long! I had to redownload EZdrummer. I had two guesses as to what could be going on. The first was that the plugin didn't set its inputs or outputs in time, but that wasn't the case here (and since I've already dealt with this before for the Roland Cloud plugins it shouldn't be an issue anymore). My second guess was that the plugin was loading resources (the drum sounds) at a moment it shouldn't be, and this ended up being it. The plugin makes some function calls that can only be run from the main GUI thread, but instead of calling these functions from the Win32 message loop like every other plugin, this plugin calls those functions at the moment the host tells the plugin that it is about to start sending audio (`effMainsChanged()`. The plugin makes the incorrect assumption that this function is called from the GUI thread, and this thus caused the plugin to never load its resources. I've added the `effMainsChanged()` to yabridge's list of 'unsafe functions' that should always be handled on the main GUI thread in 2f5d22ca17a2fc47d852c1409e36e70cdf942713.

If you want to give this a try, then you can download the latest yabridge and yabridgectl builds from the [automated builds](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) page. Or if you're running Arch/Manjaro, then you can use the `yabridge-git` and `yabridgectl-git` AUR packages instead. After downloading and installing the new version, you'll have to rerun `yabridgectl sync` to finish the update. **Note that you will also need an updated version of yabridgectl either from the automated builds page of through the `yabridgectl-git` AUR package, because on the master branch `libyabridge.so` has been renamed to `libyabridge-vst2.so` as yabridge now also also supports VST3 plugins.**

**Comment by magillos** [comment]
Long?! You replied and FIXED the issue within just a few hours!
It's all working perfectly now. Thank you!!!

**Comment by mjsuarez** [comment]
I for one think you fixed this too fast! ;)  I ran into the same issue last week, didn't see any bug reports, but thought I'd do some more testing before before reporting. Hopped on Discord for the first time to double check before reporting today and see that you already fixed it!  Keep up the great work

**Comment by robbert-vdh** [comment]
@mjsuarez Hah in the past I had never tested EZdrummer farther than the GUI because I couldn't be bothered to download all of the sound libraries (and usually the GUI is the only part of a plugin that can give issues), but as it turns out this particular plugin did some weird things that needed special handling. Usually I'd push a bug fix update after a few of these things have been accumulating for a bit, but since the master branch is now more than 600 commits ahead of 2.2.1 because of the VST3 support and a lot of other changes that sadly wasn't really possible here (and I'd very much like to prevent having to maintain multiple separate branches at the same time).
