### ISSUE TITLE
Reaper scanning of plugin not working

### ISSUE THREAD

**Issue by lyonelz96** [robbert-vdh/yabridge#77]
**Problem description**
Tried scanning a plugin (Archetype Plini from Neural DSP) and it isn't working.

**What did you expect to happen?**
For Reaper to scan the plugin and add it to the VST list.

**What actually happened?**
3 things have happened to me.

1. I successfully added the plugin (Only happened once), but when wanting to start it Reaper crashes
2. Reaper starts scanning and it kinda freezes on the plugin and this message pops up
![image](https://user-images.githubusercontent.com/43832900/105444111-3cee2d00-5c3b-11eb-95b7-19d64a2073c6.png)
3. It 'finishes' scanning with no error but the plugin wasn't added

Situation 2 happens for the VST2 only and if I don't have iLok open
Situation 3 happens all the time for VST3 whether iLok is open or not, and happens on VST2 when iLok is open

**System information**
- Plugin: Archetype Plini by Neural DSP (Requires iLok)
- Plugin type: Both VST2 and VST3
- Host: Reaper 6.20-1 (reaper-bin package from AUR)
- Operating system: Arch Linux on Zen Kernel: 5.10.9-zen1-1-zen 
- Desktop Environment/Window Manager: bspwm (Don't know if this would matter)
- Wine version: wine-6.0.r5.g310072bb ( TkG Staging Esync Fsync)
- Installation method: yabridgectl
- yabridge version: yabridge-git AUR package (2.2.1.r712.g29410e3-1)
- yabridgectl version: yabridgectl-git AUR package (2.2.1.r712.g29410e3-1)

**Debug log**

  - Log with iLok NOT running in the background: [Without iLok in the background.log](https://github.com/robbert-vdh/yabridge/files/5853702/Without.iLok.in.the.background.log)

  - Log with iLok running in the background: [With iLok running in the background.log](https://github.com/robbert-vdh/yabridge/files/5853705/With.iLok.running.in.the.background.log)

**Small note**
This plugin comes with a standalone version too and that one runs no problem if I start it with wine

**Comment by robbert-vdh** [comment]
I assume other plugins (in other prefixes) work fine, right? In both logs both the VST2 and the VST3 plugins load fine, but when time comes to actually initialize them they either crash on a Wine error (in the VST2 plugins' case) or just hang (in the VST3 plugin's case). The logs are exactly the same, which would indicate that the plugin couldn't detect iLoK running in both instances. Some other people on the yabridge Discord have been using iLoK'd plugins without issues, but perhaps this one is using some older (or very recent) version of iLoK? I can't think of any reason why this would not be a Wine issue, but an easy way to check would be to install `carla-bridges-win-git` from the AUR, open Carla, enable the bridges in the experimental tab, and then drag the plugin's .dll or .vst3 file onto there. That uses JUCE's off the shelf plugin hosting code so that gives you another implementation so you can verify whether it's a Wine issue or not.

**Comment by lyonelz96** [comment]
So I installed `carla-bridges-win-git`, enabled experimental features and enabled plugin and wine bridges option. I dragged the Plini plugin and it loads fine. I also tried loading the Spitfire BBCSO and Spitfire LABS (Both VST2 and VST3 versions) and they load up fine. I have to manually route the audio outputs in the patchbay but other than that it's fine.

Other plugins do work fine (Even on other prefixes, I set a new clean one up just to test it out).
Also, I don't know how I missed the Discord. I'll make sure to join!

**Comment by robbert-vdh** [comment]
Only thing I could think of would be that the plugin has some sort of race condition where it's blocking the Win32 message loop (which prevents the plugin from finishing initialization) until it connects to iLoK after it has iniitalized, but because it is blocking the event loop it just won't ever initialize. Have you tried any other plugins with yabridge? From the output it looks like every other plugin should work just fine.

**Comment by lyonelz96** [comment]
Yeah! The only other plugin I tried with this setup is the Spitfire BBC Symphony Orchestra and Spitfire LABS. They both work fine except for the VST3 version of the BBC Symphony Orchestra which for some reason doesn't route the output audio to Reaper. So pretty much there is audio coming out (As seen through the volume meters through the VST's interface) but no audio is coming out through Reaper. 

Again, that sound issue only happens on the VST3 version of BBC Symphony Orchestra. Other than that they both work fine. 
In terms of the Plini plugin, it's weird I actually had this working fine on earlier versions of wine and yabridge. (Like you said though, it's probably an issue with wine and not yabridge) I'll have to look further into it.

**Comment by lyonelz96** [comment]
Uhh okay. So I was using Pipewire. I decided to go back to Pulseaudio-Jack setup, retried and everything works now! Idk if it was specifically Pipewire... weird

**Comment by robbert-vdh** [comment]
Pipewire breaks more things (it's not feature complete yet), but this does sound indeed sound super strange and unrelated haha. It might just have been a weird coincidence, but I'm glad it works again for now! Let me know if you run into more things, hopefully I can be of more help with the next thing :grin:.
