### ISSUE TITLE
Can't activate W.A. Production Imperfect; probably because the font is too large

### ISSUE THREAD

**Issue by fooltopia** [robbert-vdh/yabridge#79]
I can't activate the Imperfect synth because the activation key doesn't fit in the text box. I assume that the selected font is wider than the font expected by the plugin. When I try to type in the license key, I can't type the last 3 letters. Any ideas on how to get around this?

**System information**
- Plugin: W.A. Production Imperfect
- Plugin type: VST2 (VST3 Crashes)
- Host: REAPER 6.23
- Operating system: Manjaro 
- Wine version: Wine 6.0
- Installation method: yabridgectl sync 
- yabridge version: probably commit c1b23b9 (I built the AUR package an hour ago. How can I figure out which commit was used by pamac?)
- yabridgectl version: see above.

P.s. Thanks for all your work :)

**Comment by robbert-vdh** [comment]
I'm not familiar with the plugin, but unless this is a very specific Wine bug entering a serial in a text box should just work. Are the last three characters just off screen with the font used, or would those characters still fit in the text box and they just don't show up? Even if they're off screen they'd still be entered into the text box, so just type or paste your serial number and press enter/the OK button. If that doesn't work, try using Wine Staging 6.0 instead of regular Wine 6.0. And lastly make sure that you're pasting the correct serial number (and not for instance the order number :sweat_smile:).

**Comment by fooltopia** [comment]
The box refuses to accept more characters. I can't paste the serial because it's too large. When I paste a shorter text it works. At first, I though there was an issue with pasting, so I typed it by hand. That's when I couldn't type in the last 3 characters. 

I've tried wine-staging now, and it still doesn't work. I'm sure it's the right number and I've activated other plugins from the same company before, but I'm not sure which wine version I was using. It's really weird.

**Comment by fooltopia** [comment]
I fixed it by installing the core fonts with ```winetricks corefonts```.

**Comment by robbert-vdh** [comment]
Super strange, fonts shouldn't make any difference here even if the characters cannot visually fit in the text box unless the developers of the plugin were doing some _really_ interesting things. Anyways, glad you got it working in the end!

**Comment by fooltopia** [comment]
I've seen activation boxes before that limited the number of characters you can enter which makes sense. I just never thought anyone would implement this by looking at the width of the text instead of counting the characters. 

Thanks for helping me look into it and for developing Yabridge. It has really improved my music making experience on Linux.

**Comment by siborg** [comment]
Keymaps have strange effects on u-he native plugins for example. If I
switch to Polish layout controls stop working in all native u-he plugins.
Switching back to English restores controls... Strange things happen in VST
world when it comes to keymaps, stealing focus and fonts :)

S.

**Comment by robbert-vdh** [comment]
@siborg They're probably using the scan codes rather than the key names (so their <key>Q</key> key binding will always be in the key to the right of <key>Tab</key> instead of the actual position of <key>Q</key>). You might want to email U-He about that, since they probably haven't tested it with anything other than QWERTY.

**Comment by siborg** [comment]
Will do. Cheers Robert!
