### ISSUE TITLE
lib32-boost-libs wrong jobs flag in aur PKGBUILD

### ISSUE THREAD

**Issue by mitchell-gil96** [robbert-vdh/yabridge#84]
Hi, the PKGBUILD for lib32-boost-libs fails to build due to an incorrect $(JOBS) Flag in line 96. 
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lib32-boost-libs
While the value calculated for $(JOBS) is correct, it seemingly does not pass through any flag, and when building I get the following error:

notice: could not find main target j5 
notice: assuming it is a name of file to create

j5 being the number of jobs required for my quad core cpu.

Im not sure what the correct syntax is for number of jobs with b2 boost building, but I was able to build by removing line 96 as a temporary fix.
I am raising the issue here as it seems you are the aur maintainer of the package, and it is required for building yabridge from source.

Thank you.

**Comment by robbert-vdh** [comment]
Hi,

You've probably accidentally set the `MAKEFLAGS` environment variable (either in `/etc/makepkg.conf` or in your shell configuration) to `j5` without a dash in front of it. The PKGBUILD is identical to the one of the [regular Boost package](https://github.com/archlinux/svntogit-packages/blob/packages/boost/trunk/PKGBUILD) in the repos with the `boost` headers package removed (since that's redundant), the Python and OpenMPI thing stripped out (since there are no lib32 versions of the required libraries) and of course the build flags changed to build the 32 bit version. I just checked again (on Manjaro Stable) and everything's still fine here.

What do the following commands print on your computer?

```shell
echo "$MAKEFLAGS"
grep MAKEFLAGS /etc/makepkg.conf
```

**Comment by mitchell-gil96** [comment]
Oh wow, you're right, thank you. Apparently the other compilers have just ignored my broken MAKEFLAG this whole time. Error was on my end.
