### ISSUE TITLE
Bitwig Studio not loading plugins with master branch

### ISSUE THREAD

**Issue by anoadragon453** [robbert-vdh/yabridge#9]
The v1.0.0 release version is working pretty well with Bitwig, however I was also experiencing #6 with it. In an effort to fix it, I switched to the master branch by installing the `yabridge-git` AUR package.

Now Bitwig reports that it has problems with scanning VSTs on startup.

Here's a log of it working normally (v1.0.0): https://gist.github.com/anoadragon453/821c84faa148ce45c2ab0fed2f130a38
Here's a log of the master branch (750130e4a5f098730479db05f408ec040a0c7543): https://gist.github.com/anoadragon453/418370cbe2977ffac59086ebb3a89bb8

I did not recreate any of the symlinks upon installing the new package, but as the `.so` was installed to the same location I did not consider this a problem.

Edit: Recreating the symlinks has not made a difference. Still receiving the `Could not load a shared library at '�'.` error.

It's worth noting that switching back to the `yabridge` package without touching symlinks fixes everything again, so I do think it in something in yabridge.

Edit Edit: I can confirm that the workaround mentioned in https://github.com/robbert-vdh/yabridge/issues/6#issuecomment-623722211 works as well for loading new instances of plugins.

**Comment by robbert-vdh** [comment]
Are you running Wine 5.7? Wine 5.7 somehow broke winelib builds for yabridge and similar applications. Somehow the command line arguments are not passed correctly anymore to our program. The fix for this to to temporarily just downgrade to either Wine 5.5 or Wine 5.6 and to do a clean build.

I will add the Wine version to the initialization message in the next version because it can get quite confusing haha.

**Comment by anoadragon453** [comment]
Ah! Yes I am, but I figured since I was running from wine's master branch that the regression would've been fixed already.

Do you have a link to an issue on their bugzilla I can track?

**Comment by robbert-vdh** [comment]
I don't think there is a bug report yet. When I first encountered this I couldn't find an existing bug report for it, but then I kind of forgot to file a bug report myself and I just assumed that it would have been fixed by now. The problem that I'm seeing is that the `argc` and `argv` arguments passed to our main function (in `src/wine-host/vst-host.cpp`) are somehow corrupted. I'm not sure what part of Wine or winegcc causes this though.

**Comment by anoadragon453** [comment]
Ah! May be worth asking on the forums if you're not sure where to file it under. Or just make a bug and have the develops move it to the correct location :)

**Comment by anoadragon453** [comment]
Right, wine 5.6 with commit https://github.com/robbert-vdh/yabridge/commit/750130e4a5f098730479db05f408ec040a0c7543 has solved both problems!

Thank you again for this amazing software :)

**Comment by anoadragon453** [comment]
Oh, well, actually after switching back to all symlinks pointing to `/usr/lib/libyabridge.so` I experienced #6. This issue was related to wine 5.7 though so I'll leave it closed.

**Comment by anoadragon453** [comment]
It's also worth mentioning for anyone else finding themselves here - Bitwig Studio caches information about your plugins and their loaded location in `~/.BitwigStudio/cache`. If you're switching between yabridge versions and plugin folder locations etc. you may want to close Bitwig and delete this folder before each test to ensure a clean slate every time.
