### ISSUE TITLE
VST3 version of Blucat Audio Freeware plugins causes yabridge to segfault/crash

### ISSUE THREAD

**Issue by freddano** [robbert-vdh/yabridge#91]
Thanks for giving yabridge a shot! If you're having issues with plugins not working at all or scans timing out then make sure to check out the [troubleshooting common issues](https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues) section of the readme.

**Problem description**
All VST3-versions of Blue Cat Audio causes yabridge.exe.so to segfault upon scanning in REAPER.

**What did you expect to happen?**
yabridge finishes its scan. 

**What actually happened?**
The bridge crashes and REAPER gives up on scanning. The VST2 version works fine. 

**System information**
- Plugin: BC Chorus 4 VST3(Mono).vst3 (www.bluecataudio.com)
- Plugin type: VST3
- Host: REAPER
- Operating system: OpenSUSE Tumbleweed 
 Wine version: wine-6.5 (Staging)
- Installation method: copies, yabridgectl
- yabridge version: yabridgectl 3.0.2 (cloned from github on 2021-04-09)
- yabridgectl version: 3.0.2 (cloned from github on 2021-04-09)

   `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/6284710/yabridge.log)

**Comment by freddano** [comment]
Sorry for a late reply. I tried it again, with vcrun2015 installed. It made no difference.

**Comment by robbert-vdh** [comment]
Sorry for the late response. I'm looking at this right now. Debugging Wine binaries is a bit difficult, but I'll see if I can figure out what the plugins are trying to read from, since the plugins do seem to work in the Windows version of REAPER running under Wine.

**Comment by robbert-vdh** [comment]
Good news, it's not a bug in yabridge! Bad news, it's a bug in the Bluecat Audio VST3 plugins. They probably use a handwritten VST3 implementation rather than relying on the SDK or a framework like JUCE (they do have their own framework that they sell, hopefully this bug isn't part of that), and their audio processor and edit controller objects don't expose the `IPluginBase` interface, which every plugin must support (and it's impossible to not support it). They only indirectly expose this through `IComponent`. I've added a workaround for this bug on the master branch. If you're on Arch or Manjaro, then you can temporarily switch to the `yabridge-git` AUR package to build from the master branch. If you're on any other distro, then you can grab the latest binary from the [automated builds](https://github.com/robbert-vdh/yabridge/actions?query=workflow%3A%22Automated+builds%22+branch%3Amaster) page. Don't forget to rerun `yabridgectl sync` after upgrading yabridge!

**Comment by freddano** [comment]
Absolutely fantastic work!

Thank you!

**Comment by robbert-vdh** [comment]
This fix is now in the just released yabridge 3.1.0! Feel free to open a new issue if you run into anything else.
